.github/CODEOWNERS
.github/PULL_REQUEST_TEMPLATE.md

Jira: [JIRA_TOKEN](https://bigcommercecloud.atlassian.net/browse/JIRA_TOKEN)
- update `CODEOWNERS`
- `@bigcommerce/team-b2b`
- ignacio
- leo
- use the new BC PR template
Not applicable as this is just repository settings
PR Review tool should validate `CODEOWNERS` file

fix: repo cleanup

---

apps/storefront/src/components/B3ProductList.tsx
apps/storefront/src/pages/OrderDetail/components/OrderDialog.tsx
apps/storefront/src/pages/OrderDetail/components/OrderShipping.tsx
apps/storefront/src/pages/OrderDetail/context/OrderDetailsContext.tsx
apps/storefront/src/pages/OrderDetail/index.tsx
apps/storefront/src/pages/QuickOrder/components/QuickOrderCard.tsx
apps/storefront/src/pages/QuickOrder/components/QuickorderTable.tsx
apps/storefront/src/pages/QuotesList/index.tsx
apps/storefront/src/pages/Registered/RegisterComplete.tsx
apps/storefront/src/pages/ShoppingListDetails/components/ChooseOptionsDialog.tsx
apps/storefront/src/pages/ShoppingListDetails/components/ShoppingDetailCard.tsx
apps/storefront/src/pages/ShoppingListDetails/components/ShoppingDetailTable.tsx
apps/storefront/src/pages/quote/components/QuoteDetailSummary.tsx
apps/storefront/src/pages/quote/components/QuoteDetailTable.tsx
apps/storefront/src/shared/service/b2b/graphql/product.ts
apps/storefront/src/store/selectors.ts
apps/storefront/src/types/orderDetail.ts
apps/storefront/src/utils/b2bGetVariantImageByVariantInfo.ts
apps/storefront/src/utils/b3CurrencyFormat.ts
apps/storefront/src/utils/b3Product/shared/config.ts
apps/storefront/src/utils/index.ts

Jira: [bun2580](https://bigc-b2b.atlassian.net/browse/BUN-2580)
[bun2523](https://bigc-b2b.atlassian.net/browse/BUN-2523)
[bun2491](https://bigc-b2b.atlassian.net/browse/BUN-2491)
[bun2513](https://bigc-b2b.atlassian.net/browse/BUN-2513)
fix buyer portal bugs
revert
1. bun2580
2.bun2523
3.bun2491
4.bun2513

fix: brian/feat/sprint56

---

.github/workflows/deploy.yml
.github/workflows/tests.yaml
apps/storefront/codegen.ts
apps/storefront/package.json
apps/storefront/src/components/captcha/Captcha.tsx
apps/storefront/src/pages/ForgotPassword/index.test.tsx
apps/storefront/src/pages/ForgotPassword/index.tsx
apps/storefront/src/pages/Login/config.ts
apps/storefront/src/pages/Registered/RegisterComplete.tsx
apps/storefront/src/shared/service/b2b/graphql/checkout.ts
apps/storefront/src/shared/service/b2b/graphql/recaptcha.ts
apps/storefront/src/shared/service/request/fetch.ts
apps/storefront/src/store/slices/theme.ts
apps/storefront/src/utils/b3Storage.ts
apps/storefront/tests/assertQueryParams.tsx
apps/storefront/tests/components/ThemeFrame.test.tsx
apps/storefront/tests/components/b3table/B3Table.test.tsx
apps/storefront/tests/components/quickOrder/QuickOrder.test.tsx
apps/storefront/tests/mockServer.ts
apps/storefront/tests/test-utils.tsx
apps/storefront/vite.config.ts
packages/eslint-config-b2b/.eslintrc.js
yarn.lock

This commit sets the basis for testing across the app.
Adds several testing tools used to ensure the app works correctly.
Revert this PR
This PR is mostly about unit testing, the build should prove everything works.

test: add basic tests for the ForgotPassword page

---

apps/storefront/src/components/layout/B3Mainheader.tsx
apps/storefront/src/pages/QuickOrder/components/QuickOrderFooter.tsx
apps/storefront/src/pages/QuickOrder/index.tsx
apps/storefront/src/pages/ShoppingListDetails/components/ShoppingDetailFooter.tsx
apps/storefront/src/pages/ShoppingListDetails/components/ShoppingDetailTable.tsx
apps/storefront/src/pages/ShoppingListDetails/index.tsx

Jira: [BUN-2662](https://bigc-b2b.atlassian.net/browse/BUN-2662)
B2B Edition Shopping Lists do not have "Add to Cart" Option while logged in as a B2C User
undo this pr

fix: bun2662 bc account cart action

---

apps/storefront/src/components/layout/B3Mainheader.tsx
apps/storefront/src/hooks/useB3AppOpen.ts
apps/storefront/src/pages/QuickOrder/components/QuickOrderFooter.tsx
apps/storefront/src/pages/QuickOrder/index.tsx
apps/storefront/src/pages/ShoppingListDetails/components/ShoppingDetailFooter.tsx
apps/storefront/src/pages/ShoppingListDetails/components/ShoppingDetailTable.tsx
apps/storefront/src/pages/ShoppingListDetails/index.tsx
apps/storefront/src/pages/ShoppingLists/AddEditShoppingLists.tsx
apps/storefront/src/shared/service/b2b/graphql/shoppingList.ts
apps/storefront/src/utils/b3ShoppingList/b3ShoppingList.ts
packages/global-b3/index.ts

Jira: [BUN-2601](https://bigc-b2b.atlassian.net/browse/BUN-2601)
[BUN-2662](https://bigc-b2b.atlassian.net/browse/BUN-2662)
[BUN-2621](https://bigcommercecloud.atlassian.net/browse/BUN-2621)
1. description is not escaped, graphql reports an error, description needs to be escaped
When we use strings in GraphQL queries or mutations, if the string contains special characters (such as newlines, double quotes, etc.), these characters may be mistaken as part of the syntax, resulting in parsing errors. For example, unescaped newlines can break the structure of the query and prevent it from parsing correctly
If we use newlines directly in the query, it will cause an error
mutation { updateDescription(description: "test\n") }
This causes parsing errors because newlines are mistaken for part of the …

feat: sprint57 Iteration task

---

apps/storefront/src/pages/Invoice/index.tsx
apps/storefront/src/shared/service/b2b/graphql/invoice.ts

Jira: [BUN-2683](https://bigc-b2b.atlassian.net/browse/BUN-2683)
invoice export csv  add lang
1. invoicesExport adds field lang
2. Modify invoicesExport graphql and change it to a variable
undo pr

fix: invoice export csv add lang

---

apps/storefront/src/hooks/dom/utils.ts
apps/storefront/src/utils/b3Product/b3Product.ts

Jira:[BUN-2667](https://bigc-b2b.atlassian.net/browse/BUN-2667)
issue: Converting a B2B edition cart to a quote removes selected options
* When adding products from cart to quote, data was not collected correctly, resulting in the clearing of selected options.
undo pr
https://github.com/bigcommerce/b2b-buyer-portal/assets/80307788/e0475b21-dd9b-4ca1-a4e4-40797bcc5133

fix: add product from cart to quote

---

apps/storefront/src/shared/routes/index.tsx
apps/storefront/src/utils/b3CheckPermissions/index.ts
apps/storefront/src/utils/index.ts

Jira:[BUN-2668](https://bigc-b2b.atlassian.net/browse/BUN-2668)
feature management settings do not take effect
Feature management cancel shopping list, quote, invoice, etc.,
The buyer portal still displays shopping list, quote, invoice, etc. menu bar
undo pr
https://github.com/bigcommerce/b2b-buyer-portal/assets/80307788/30dc085e-2ce5-4bf0-b2c2-dd095efac801

fix: feature management settings do not take effect

---

apps/storefront/src/pages/Login/config.ts
apps/storefront/src/pages/Registered/RegisterComplete.tsx
apps/storefront/src/shared/service/b2b/api/global.ts
apps/storefront/src/shared/service/b2b/api/login.ts
apps/storefront/src/shared/service/b2b/api/order.ts
apps/storefront/src/shared/service/b2b/api/proxy.ts
apps/storefront/src/shared/service/b2b/api/register.ts
apps/storefront/src/shared/service/b2b/index.ts
apps/storefront/src/utils/b3Product/b3Product.ts
apps/storefront/src/utils/loginInfo.ts

Jira: [BUN-2623](https://bigc-b2b.atlassian.net/browse/BUN-2623)
recommended fix: remove proxy endpoints, replace with specific API endpoints implementing only the required functionality with proper access controls.
undo pr
https://github.com/user-attachments/assets/6206bd36-7a07-43ea-9bdc-d78a33a89293
https://github.com/user-attachments/assets/022f7e47-cd68-40ef-b66c-d54b6858f651

fix: delete v2/proxy interface and use the corresponding interface

---

apps/storefront/src/components/upload/BulkUploadTable.tsx
packages/lang/locales/en.json

Jira: [BUN-2670](https://bigc-b2b.atlassian.net/browse/BUN-2670)
update the wording in csv upload results
undo pr

fix: bun2670 update the wording in csv upload results

---

apps/storefront/src/pages/Registered/RegisterComplete.tsx

Jira: [BUN-2744](https://bigc-b2b.atlassian.net/browse/BUN-2744)
send BC New Customer Welcome Email to Personal Account Customers when registering via storefront Buyer Portal
undo pr

fix: create bc user to add mail sending

---

apps/storefront/src/pages/AccountSetting/utils.ts
apps/storefront/src/shared/service/b2b/graphql/accountSetting.ts

Jira: [BUN-2723](https://bigc-b2b.atlassian.net/browse/BUN-2723)
Account Settings Page Not Displaying Role
undo pr

fix: bun2723 account settings page displaying role

---

apps/storefront/src/pages/Registered/RegisteredAccount.tsx
apps/storefront/src/shared/service/b2b/graphql/users.ts

Jira: [BUN-2741](https://bigc-b2b.atlassian.net/browse/BUN-2741)
duplicate registration issue
undo pr
https://github.com/user-attachments/assets/6f3c66c6-ff77-4c06-a6f5-7385036d06c2

fix: duplicate registration issue

---

apps/storefront/vite.config.ts

**Jira: [BUN-2784](https://bigc-b2b.atlassian.net/browse/BUN-2784)
PageSpeed checks that the react-setup file takes too long to parse.
​
react-setup is unpacked to perform an optimization
undo pr
old: 
new:
**

fix: allocate different dependent modules

---

apps/storefront/src/components/ThemeFrame.tsx

Jira: [BUN-2761](https://bigc-b2b.atlassian.net/browse/BUN-2761)
css override duplicating in html
undo pr
https://github.com/user-attachments/assets/d3c348a3-bd21-4930-a66a-3c424ff4d48b

fix: css override duplicating in html

---

apps/storefront/src/pages/OrderDetail/components/OrderDialog.tsx
apps/storefront/src/pages/OrderDetail/components/OrderShipping.tsx
apps/storefront/src/pages/OrderDetail/context/OrderDetailsContext.tsx
apps/storefront/src/pages/OrderDetail/index.tsx
apps/storefront/src/pages/order/Order.tsx
apps/storefront/src/shared/service/b2b/graphql/orders.ts
apps/storefront/src/types/orderDetail.ts

Jira: [BUN-2681](https://bigc-b2b.atlassian.net/browse/BUN-2681)
limit purchases of invisible products
undo pr
https://github.com/user-attachments/assets/2d95dcfd-0ab3-45f2-9411-8e4beeb75c5c

fix: bun2681 limit purchases of invisible products

---

apps/storefront/src/pages/OrderDetail/components/OrderHistory.tsx

Jira: [BUN-2719](https://bigc-b2b.atlassian.net/browse/BUN-2719)
time formatting
undo pr

fix: time formatting bun2719

---

apps/storefront/src/App.tsx

Jira: [BUN-2742](https://bigc-b2b.atlassian.net/browse/BUN-2742)
add to quote After the product is added, the browser returns a blank page. You should actually return to the pdp page
undo pr
https://github.com/user-attachments/assets/144b2bbb-e6dc-4d08-a1bd-54aa92964342

fix: empty Page showing when you back using browser button

---

apps/storefront/src/pages/OrderDetail/components/OrderAction.tsx
packages/lang/locales/en.json

Jira: [BUN-1641](https://bigc-b2b.atlassian.net/browse/BUN-1641)
I'm changing the message of the payments details when seeing any order detail because is confusing for buyers and sellers who still owe payment via Invoice
Revert PR

fix: updating message for po payments

---

apps/storefront/src/pages/QuickOrder/components/QuickAdd.tsx
apps/storefront/src/pages/QuickOrder/components/QuickOrderFooter.tsx
apps/storefront/src/pages/QuickOrder/components/QuickOrderPad.tsx
apps/storefront/src/pages/QuickOrder/components/QuickorderTable.tsx
apps/storefront/src/pages/QuickOrder/index.tsx
apps/storefront/src/pages/QuickOrder/utils.ts

Jira: [BUN-2883](https://bigc-b2b.atlassian.net/browse/BUN-2883)
After setting the maximum or minimum purchase quantity of the product, no corresponding prompt is given
Solution: Get the maximum or minimum number of products to buy, and then get the same products in the cart and add them to determine whether the maximum number is greater or less than the minimum number
undo pr
https://github.com/user-attachments/assets/20f0e878-c720-4d2f-925f-83616f3f566d
https://github.com/user-attachments/assets/fe9847b6-0d7f-47b4-8dd9-5bbc996632a9
https://github.com/user-attachments/assets/f79b39e9-c7ea-413a-8990-2febfaf1f15e

fix: add products to cart to verify maximum quantity

---

apps/storefront/src/pages/OrderDetail/components/OrderAction.tsx

Jira: [BUN-2796](https://bigc-b2b.atlassian.net/browse/BUN-2796)
control shoppingList button
undo pr
https://github.com/user-attachments/assets/27c3590a-b4cc-4b56-b2c2-af0923276093

fix: control shoppingList button bun2796 

---

apps/storefront/src/pages/AccountSetting/index.tsx

Jira: [BUN-2885](https://bigc-b2b.atlassian.net/browse/BUN-2885)
remove bc interface
This interface function already includes the function of the bc interface, so the call to the bc interface is removed here
undo pr
https://github.com/user-attachments/assets/3274e6e5-d430-4cf1-a8e5-aa587c0b9da3

fix: bun2885 remove bc interface

---

apps/storefront/src/components/RegisteredCloseButton.tsx
apps/storefront/src/pages/Login/index.tsx

Jira: [BUN-2869](https://bigc-b2b.atlassian.net/browse/BUN-2869)
fix logout issues
Page flashing issue when exiting
undo pr
https://github.com/user-attachments/assets/049374d4-0448-42a3-86f8-6e1178019b71

fix: fix logout issues

---

apps/storefront/src/pages/QuoteDetail/index.tsx
apps/storefront/src/utils/storefrontConfig.ts

Jira: [B2B-1248](https://bigcommercecloud.atlassian.net/browse/B2B-1248)
adds quote_auto_quoting functionality to control the buyerportal quote detail process to checkout button
undo pr
https://github.com/user-attachments/assets/773dfb08-55dd-401f-92d5-587e69dba0cc
[B2B-1248]: https://bigcommercecloud.atlassian.net/browse/B2B-1248?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: add quote_auto_quoting feature

---

apps/storefront/src/components/B3Dialog.tsx
apps/storefront/src/pages/QuoteDraft/index.tsx
apps/storefront/src/pages/quote/components/QuoteSubmissionResponse.tsx
apps/storefront/src/store/slices/global.ts
apps/storefront/src/utils/storefrontConfig.ts
packages/lang/locales/en.json

Jira: [B2B-1249](https://bigcommercecloud.atlassian.net/browse/B2B-1249)
add quote submission response
undo pr
https://github.com/user-attachments/assets/0998c472-fd12-4e3a-9875-493f9dde308a
[B2B-1249]: https://bigcommercecloud.atlassian.net/browse/B2B-1249?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: quote submission message dialog

---

apps/storefront/src/pages/Invoice/components/InvoiceFooter.tsx
apps/storefront/src/pages/Invoice/index.tsx
apps/storefront/src/pages/Invoice/utils/payment.ts
apps/storefront/src/shared/service/b2b/graphql/invoice.ts

Jira: [SUP-1866](https://bigcommercecloud.atlassian.net/browse/SUP-1866)
invocie number rounding and adding parameters
undo pr
Example: Keeping two decimal places
Adding parameters to the interface
[SUP-1866]: https://bigcommercecloud.atlassian.net/browse/SUP-1866?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: invocie number rounding and adding parameters

---

apps/storefront/src/components/form/B3ControlPicker.tsx
apps/storefront/src/components/ui/B3Picker.tsx

Jira: [B2B-1019](https://bigcommercecloud.atlassian.net/browse/B2B-1019)
the time component cannot be clicked on the mobile
undo pr
https://github.com/user-attachments/assets/a6938889-dd1f-46ae-9441-46dda337fb36
[B2B-1019]: https://bigcommercecloud.atlassian.net/browse/B2B-1019?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: resolve that the time component cannot be clicked on the mobile

---

apps/storefront/src/pages/quote/components/QuoteTable.tsx
apps/storefront/src/utils/b3Product/b3Product.ts
packages/tsconfig/vite.json

quoteDraft： unit price calculated according to quantity
undo pr
https://github.com/user-attachments/assets/ccd6614f-5b8e-4209-90f9-fa3efc9fda85

fix: unit price calculated according to quantity

---

apps/storefront/src/pages/OrderDetail/components/OrderAction.tsx
apps/storefront/src/pages/OrderDetail/context/OrderDetailsContext.tsx
apps/storefront/src/pages/OrderDetail/shared/B2BOrderData.ts
apps/storefront/src/types/orderDetail.ts
packages/lang/locales/en.json

Jira: [B2B-1425](https://bigcommercecloud.atlassian.net/browse/B2B-1425)
display coupon information in order details
undo pr
[B2B-1425]: https://bigcommercecloud.atlassian.net/browse/B2B-1425?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: display coupon information in order details

---

apps/storefront/src/components/layout/B3StatusNotification.tsx
apps/storefront/src/pages/QuoteDetail/index.tsx
apps/storefront/src/pages/QuoteDraft/index.tsx

Jira: [B2B-1352](https://bigcommercecloud.atlassian.net/browse/B2B-1352)
Blank quote showing through when Quote submission message is displayed
undo pr
https://github.com/user-attachments/assets/9828f1a9-e4da-4d11-a0d6-6d10072a2fa2
[B2B-1352]: https://bigcommercecloud.atlassian.net/browse/B2B-1352?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: quote submission message show quote info

---

apps/storefront/src/App.tsx
apps/storefront/src/pages/Login/index.tsx
apps/storefront/src/shared/service/b2b/graphql/register.ts
apps/storefront/src/utils/loginInfo.ts

Reverts bigcommerce/b2b-buyer-portal#135

revert: "fix: set permissions consumed from new query"

---

apps/storefront/src/App.tsx

Jira: [B2B-1458](https://bigcommercecloud.atlassian.net/browse/B2B-1458)
page stuck on loading screen with anchor links
undo pr
https://github.com/user-attachments/assets/4f94ac4e-9b09-427c-8bf3-ac599133bb36
[B2B-1458]: https://bigcommercecloud.atlassian.net/browse/B2B-1458?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: page stuck on loading screen with anchor links

---

.github/workflows/deploy-production-tier1-only.yml
.github/workflows/deploy-production.yml
.github/workflows/deploy-staging.yml
.github/workflows/deploy.yml

Jira: [B2B-1585](https://bigcommercecloud.atlassian.net/browse/B2B-1585)
* Using a completely independent environment for Tier1
* Avoid auto Tier1 deployment, there is an issue with headless stores.
Rever this PR
NA
[B2B-1585]: https://bigcommercecloud.atlassian.net/browse/B2B-1585?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(b2b-1585): support tier1 independent environment

---

apps/storefront/package.json
apps/storefront/src/buyerPortal.ts
apps/storefront/vite.config.ts
package.json
turbo.json

Jira: [1585](https://bigcommercecloud.atlassian.net/browse/1585)
Include `tier1` to get proper request for production tier 1 stores
Rever this PR
NA

fix: remove`tier1` as build mode

---

apps/storefront/src/pages/Login/index.tsx
apps/storefront/src/shared/service/bc/api/login.ts
apps/storefront/src/utils/loginInfo.ts

Jira: [B2B-1544](https://bigcommercecloud.atlassian.net/browse/B2B-1544)
A validation was implemented to ensure that login requests are only made for`'bigcommerce'` platform stores.
Revert this PR
NA
[B2B-1544]: https://bigcommercecloud.atlassian.net/browse/B2B-1544?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: validate platform before made login requests

---

apps/storefront/src/pages/quote/components/QuoteTable.tsx

Jira: [B2B-1041](https://bigcommercecloud.atlassian.net/browse/B2B-1041)
Jira: [B2B-1552](https://bigcommercecloud.atlassian.net/browse/B2B-1552)
After modifying the product option on the quote draft page and submitting the quote, the Tax total reported is not correct.
undo pr
https://github.com/user-attachments/assets/720dbf48-310c-43cd-8d1c-d526c8ce1764
[B2B-1041]: https://bigcommercecloud.atlassian.net/browse/B2B-1041?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[B2B-1552]: https://bigcommercecloud.atlassian.net/browse/B2B-1552?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: quote draft tax price

---

apps/storefront/.env-example

NO JIRA
per this thread, this value is wrong https://bigcommerce.slack.com/archives/C01SAU2HH1V/p1731456396702289?thread_ts=1715630373.016079&cid=C01SAU2HH1V
revert

fix: app client id change in env example

---

apps/storefront/.env-example

Reverts bigcommerce/b2b-buyer-portal#158
Reverting as is the correct client id

Revert "fix: app client id change in env example"

---

apps/storefront/src/components/layout/B3CompanyHierarchy.tsx
apps/storefront/src/components/layout/B3Mainheader.tsx
apps/storefront/src/components/outSideComponents/B3CompanyHierarchyExternalButton.tsx
apps/storefront/src/components/outSideComponents/B3MasquradeGobalTip.tsx
apps/storefront/src/pages/CompanyHierarchy/components/TableTree.tsx
apps/storefront/src/pages/CompanyHierarchy/index.tsx
apps/storefront/src/shared/routes/config.ts
apps/storefront/src/utils/loginInfo.ts
apps/storefront/src/utils/masquerade.ts

Jira: [B2B-1567](https://bigcommercecloud.atlassian.net/browse/B2B-1567)
bugs fix
undo pr
https://github.com/user-attachments/assets/00610bc6-0b29-4d06-a08e-907152a45a25
[B2B-1567]: https://bigcommercecloud.atlassian.net/browse/B2B-1567?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: b2b-1567 bugs

---

apps/storefront/src/components/layout/B3CompanyHierarchy.tsx
apps/storefront/src/components/layout/B3Nav.tsx
apps/storefront/src/components/outSideComponents/B3CompanyHierarchyExternalButton.tsx
apps/storefront/src/components/outSideComponents/B3MasquradeGobalTip.tsx
apps/storefront/src/constants/index.ts
apps/storefront/src/pages/CompanyHierarchy/components/HierarchyDialog.tsx
apps/storefront/src/pages/CompanyHierarchy/components/TableTree.tsx
apps/storefront/src/pages/CompanyHierarchy/index.tsx
apps/storefront/src/pages/Login/index.tsx
apps/storefront/src/pages/QuoteDetail/index.tsx
apps/storefront/src/shared/routes/config.ts
apps/storefront/src/shared/routes/index.tsx
apps/storefront/src/shared/service/b2b/graphql/global.ts
apps/storefront/src/shared/service/b2b/index.ts
apps/storefront/src/store/slices/company.ts
apps/storefront/src/types/company.ts
apps/storefront/src/utils/b3CheckPermissions/index.ts
apps/storefront/src/utils/loginInfo.ts
apps/storefront/src/utils/masquerade.ts

Jira: [B2B-1567](https://bigcommercecloud.atlassian.net/browse/B2B-1567)
1. remove superadmin company hierarchy
2. add subsidiariesCompany permission
3. save current path subsidiariescompany Permission
undo pr
https://github.com/user-attachments/assets/090bd1b1-318e-4321-b100-3bd02069c99b
[B2B-1567]: https://bigcommercecloud.atlassian.net/browse/B2B-1567?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: remove superadmin company hierarchy and add subsidiariesCompany

---

apps/storefront/src/pages/Invoice/index.tsx
apps/storefront/src/pages/OrderDetail/components/OrderAction.tsx

Jira: [B2B-1566](https://bigcommercecloud.atlassian.net/browse/B2B-1566)
order detail SL btn
undo pr
[B2B-1566]: https://bigcommercecloud.atlassian.net/browse/B2B-1566?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: order detail SL btn

---

apps/storefront/src/components/B3CustomForm.tsx
apps/storefront/src/components/form/B2BControlMultiTextField.tsx
apps/storefront/src/components/form/index.ts
apps/storefront/src/pages/QuoteDraft/index.tsx
apps/storefront/src/pages/quote/components/ContactInfo.tsx
apps/storefront/src/pages/quote/components/QuoteInfoAndExtrafieldsItem.tsx
apps/storefront/src/shared/service/b2b/graphql/quote.ts
apps/storefront/src/store/slices/quoteInfo.ts
apps/storefront/src/types/quotes.ts
packages/lang/locales/en.json

Jira: [B2B-1744](https://bigcommercecloud.atlassian.net/browse/B2B-1744)
quote add cc email
undo pr
https://github.com/user-attachments/assets/d82e98b8-faa4-4235-991f-4e860a688b61
[B2B-1744]: https://bigcommercecloud.atlassian.net/browse/B2B-1744?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: quote add cc email

---

.circleci/config.yml

Jira: [APPSEC-767](https://bigcommercecloud.atlassian.net/browse/APPSEC-767)
Adding gitleaks to run within circleci. To scan for secrets within the codebase
Revert this PR
https://app.circleci.com/pipelines/github/bigcommerce/b2b-buyer-portal/212/workflows/a86b2765-b378-43b2-9969-49add5ec875d/jobs/356
[APPSEC-767]: https://bigcommercecloud.atlassian.net/browse/APPSEC-767?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: adding secret scanning

---

apps/storefront/src/components/outSideComponents/B3CompanyHierarchyExternalButton.tsx
apps/storefront/src/components/ui/B2BAutoCompleteCheckbox.tsx
apps/storefront/src/pages/CompanyHierarchy/components/CompanyTableRowCard.tsx
apps/storefront/src/pages/CompanyHierarchy/components/TableTree.tsx
apps/storefront/src/pages/CompanyHierarchy/components/types.tsx
apps/storefront/src/pages/Invoice/index.tsx
apps/storefront/src/pages/order/Order.tsx

Jira: [B2B-1901](https://bigcommercecloud.atlassian.net/browse/B2B-1901)
add mobile version company hierarchy
undo pr
https://github.com/user-attachments/assets/241320fd-cfe2-4d52-892c-10ebaeadce8d
[B2B-1901]: https://bigcommercecloud.atlassian.net/browse/B2B-1901?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: mobile version company hierarchy

---

.cspell.json
apps/storefront/src/hooks/useGetCountry.ts
apps/storefront/src/pages/Address/components/AddressForm.tsx
apps/storefront/src/pages/Address/shared/getAddressFields.ts
apps/storefront/src/pages/Registered/RegisteredDetail.tsx
apps/storefront/src/pages/RegisteredBCToB2B/index.tsx

Jira: [B2B-1773](https://bigcommercecloud.atlassian.net/browse/B2B-1773)
determine whether the state field is required based on the country
**application scenario:**
address
registration
quoteDraft
Revert PR
https://github.com/user-attachments/assets/c7fb652e-9e46-4648-a146-972e8d918ca7
https://github.com/user-attachments/assets/6591f0db-b6ad-47dd-b5f8-97998a161e32
[B2B-1773]: https://bigcommercecloud.atlassian.net/browse/B2B-1773?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: determine whether the state field is required based on the country

---

.cspell.json
apps/storefront/src/components/B3ProductList.tsx
apps/storefront/src/pages/OrderDetail/components/OrderAction.tsx
apps/storefront/src/pages/OrderDetail/components/OrderShipping.tsx
apps/storefront/src/pages/OrderDetail/shared/B2BOrderData.ts
apps/storefront/src/types/products.ts
apps/storefront/src/utils/b3Product/b3Product.ts
packages/lang/locales/en.json

Jira: [B2B-1896](https://bigcommercecloud.atlassian.net/browse/B2B-1896)
order detail display promotion discount
undo pr
[B2B-1896]: https://bigcommercecloud.atlassian.net/browse/B2B-1896?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: order detail display promotion discount

---

apps/storefront/src/App.tsx
apps/storefront/src/components/extraTip/GlobalDialog.tsx
apps/storefront/src/components/index.ts
apps/storefront/src/components/layout/B3AccountInfo.tsx
apps/storefront/src/components/layout/B3RenderRouter.tsx
apps/storefront/src/components/outSideComponents/B3HoverButton.tsx
apps/storefront/src/components/outSideComponents/B3MasqueradeGlobalTip.tsx
apps/storefront/src/constants/index.ts
apps/storefront/src/hooks/dom/useOpenPDP.ts
apps/storefront/src/pages/AccountSetting/index.tsx
apps/storefront/src/pages/ForgotPassword/index.test.tsx
apps/storefront/src/pages/ForgotPassword/index.tsx
apps/storefront/src/pages/Login/config.ts
apps/storefront/src/pages/Login/index.tsx
apps/storefront/src/shared/routes/index.tsx
apps/storefront/src/shared/service/request/b3Fetch.ts
apps/storefront/src/store/slices/global.ts
apps/storefront/src/types/login.ts
apps/storefront/src/utils/b3AccountItem.ts
packages/lang/locales/en.json

Jira: [B2B-1947](https://bigcommercecloud.atlassian.net/browse/B2B-1947)
1. optimize the login page type and modify the verification of cspell
2. guest user login displays an error message in checkout
Revert PR
**Verification 1:**
https://github.com/user-attachments/assets/ccf62e37-3a9e-447e-97a2-f420a251253b
https://github.com/user-attachments/assets/cfc4135c-cdbf-42d7-9a77-f61ef19a85a3
**Verification 2:**
https://github.com/user-attachments/assets/024aa71a-45f2-4b70-bca9-cbf815a9efc7
[B2B-1947]: https://bigcommercecloud.atlassian.net/browse/B2B-1947?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: guest user login displays an error message in checkout

---

apps/storefront/.eslintrc.json
apps/storefront/src/components/filter/B3Filter.tsx
apps/storefront/src/components/filter/B3FilterMore.tsx
apps/storefront/src/pages/Address/index.tsx
apps/storefront/src/pages/Invoice/index.tsx
apps/storefront/src/pages/QuickOrder/components/QuickOrderB2BTable.tsx
apps/storefront/src/pages/QuickOrder/components/QuickOrderFooter.tsx
apps/storefront/src/pages/QuickOrder/index.tsx
apps/storefront/src/pages/QuotesList/index.tsx
apps/storefront/src/pages/ShoppingLists/index.tsx
apps/storefront/src/pages/UserManagement/index.tsx
apps/storefront/src/pages/order/Order.tsx
apps/storefront/src/pages/order/config.ts
apps/storefront/src/utils/b3Price.ts
apps/storefront/src/utils/index.ts
apps/storefront/tests/components/quickOrder/QuickOrder.test.tsx

Jira: [B2B-1854](https://bigcommercecloud.atlassian.net/browse/B2B-1854)
show quick order price by setting
modify spelling
undo pr
[B2B-1854]: https://bigcommercecloud.atlassian.net/browse/B2B-1854?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: modify spelling and show quick order price by setting

---

apps/storefront/src/pages/QuoteDraft/index.tsx
apps/storefront/src/store/slices/quoteInfo.ts

Jira: [B2B-1498](https://bigcommercecloud.atlassian.net/browse/B2B-1498)
create quote add cc email
undo pr
https://github.com/user-attachments/assets/fbde2851-ed6f-4ae7-83e7-88dd399bd9a0
[B2B-1498]: https://bigcommercecloud.atlassian.net/browse/B2B-1498?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: hotfix create quote add cc email

---

apps/storefront/src/components/B3DropDown.tsx
apps/storefront/src/index.d.ts
apps/storefront/src/utils/basicConfig.ts

Jira: [B2B-2098](https://bigcommercecloud.atlassian.net/browse/B2B-2098)
Disabling logout for catalyst
revert
[B2B-2098]: https://bigcommercecloud.atlassian.net/browse/B2B-2098?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: disabling logout button in catalyst

---

apps/storefront/src/pages/quote/components/ContactInfo.tsx
apps/storefront/src/pages/quote/components/QuoteInfo.tsx

Jira: [B2B-2112](https://bigcommercecloud.atlassian.net/browse/B2B-2112)
1. quote add companyName field
2. modify spelling
Revert
https://github.com/user-attachments/assets/f0160b63-ca93-46d0-9e33-1663f1537482
[B2B-2112]: https://bigcommercecloud.atlassian.net/browse/B2B-2112?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: quote add companyName field and modify spelling

---

apps/storefront/src/pages/Login/index.tsx

Jira: [B2B-2111](https://bigcommercecloud.atlassian.net/browse/B2B-2111)
force password reset on next login setting not respected when logging in with the Buyer Portal
Revert
https://github.com/user-attachments/assets/9eaf0671-9988-42c2-bd08-d28331240b6d
[B2B-2111]: https://bigcommercecloud.atlassian.net/browse/B2B-2111?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: password reset on next login setting not respected when logging

---

apps/storefront/src/utils/b3Product/b3Product.ts

Jira: [B2B-1561](https://bigcommercecloud.atlassian.net/browse/B2B-1561)
quote Tax is displayed as NaN when the price is zero
undo pr
https://github.com/user-attachments/assets/7bfb0a9d-69d2-40f0-b589-5acba698a9fa
[B2B-1561]: https://bigcommercecloud.atlassian.net/browse/B2B-1561?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: quote Tax is displayed as NaN when the price is zero

---

apps/storefront/src/pages/Dashboard/index.tsx

Jira: [B2B-2141](https://bigcommercecloud.atlassian.net/browse/B2B-2141)
Revert
Mostly automated refactors through the IDE.
[B2B-2141]: https://bigcommercecloud.atlassian.net/browse/B2B-2141?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

refactor(dashboard): create a useData hook with basic information

---

apps/storefront/src/pages/InvoiceDetail/index.tsx
apps/storefront/src/shared/routes/index.tsx

Jira: [B2B-2153](https://bigcommercecloud.atlassian.net/browse/B2B-2153)
Remove unused page
Revert
n/a
[B2B-2153]: https://bigcommercecloud.atlassian.net/browse/B2B-2153?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(invoice-details): remove this page, it is not used

---

apps/storefront/src/pages/ShoppingLists/index.tsx

Jira: [B2B-2141](https://bigcommercecloud.atlassian.net/browse/B2B-2141)
Revert
Automated refactor
[B2B-2141]: https://bigcommercecloud.atlassian.net/browse/B2B-2141?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

refactor(shopping-list): create a useData hook with basic information

---

apps/storefront/src/pages/QuotesList/index.tsx

Revert
Mostly automated changes.

refactor(quotes): create a useData hook with basic information

---

apps/storefront/src/pages/Invoice/index.tsx

Jira: [B2B-2148](https://bigcommercecloud.atlassian.net/browse/B2B-2148)
Revert
Mostly automated refactoring through the IDE.
[B2B-2148]: https://bigcommercecloud.atlassian.net/browse/B2B-2148?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

refactor(invoice): create a useData hook with basic information

---

apps/storefront/src/pages/order/Order.tsx

Jira: [B2B-2146](https://bigcommercecloud.atlassian.net/browse/B2B-2146)
Revert
Mostly automated refactors through the IDE.
[B2B-2146]: https://bigcommercecloud.atlassian.net/browse/B2B-2146?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

refactor(order): create a useData hook with basic information

---

apps/storefront/src/components/ui/B2BAutoCompleteCheckbox.tsx

Jira: [B2B-2132](https://bigcommercecloud.atlassian.net/browse/B2B-2132)
display full company name
undo pr
https://github.com/user-attachments/assets/a33530e0-b5a4-4c54-b170-4ae35c250a11
[B2B-2132]: https://bigcommercecloud.atlassian.net/browse/B2B-2132?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: display full company name

---

apps/storefront/src/pages/AccountSetting/index.tsx

Jira: [B2B-2158](https://bigcommercecloud.atlassian.net/browse/B2B-2158)
Revert
This was an automated refactor via the IDE.
[B2B-2158]: https://bigcommercecloud.atlassian.net/browse/B2B-2158?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

refactor(account-settings): create a useData hook with basic information

---

apps/storefront/src/pages/ShoppingListDetails/index.tsx

Jira: [B2B-2155](https://bigcommercecloud.atlassian.net/browse/B2B-2155)
- Move fetching/acl code out of the presentation code
- Manual testing
[B2B-2155]: https://bigcommercecloud.atlassian.net/browse/B2B-2155?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

B2B-2155 refactor async function into useData within ShoppingListDetails

---

apps/storefront/src/pages/QuoteDetail/index.tsx

Jira: [B2B-2160](https://bigcommercecloud.atlassian.net/browse/B2B-2160)
- add `useData` hoot as first step refactoring to move data fetching/business logic away from presentational code
- revert this PR
- manual
[B2B-2160]: https://bigcommercecloud.atlassian.net/browse/B2B-2160?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

B2B-2160 refactor QuoteDetail - create a useData hook with basic information

---

apps/storefront/src/pages/ForgotPassword/index.test.tsx

Jira: [B2B-2203](https://bigcommercecloud.atlassian.net/browse/B2B-2203)
fix broken test
Revert
[B2B-2203]: https://bigcommercecloud.atlassian.net/browse/B2B-2203?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: correct the tests

---

apps/storefront/src/components/HeadlessController.tsx
apps/storefront/src/pages/PDP/index.tsx
apps/storefront/src/pages/PDP/useAddedToShoppingListAlert.tsx

Jira: [B2B-2165](https://bigcommercecloud.atlassian.net/browse/B2B-2165)
- Move move data fetching and reshaping logic into useData to move it away from presentation code
- Simply implementations by moving values closer to their usage
- Manual 
[B2B-2165]: https://bigcommercecloud.atlassian.net/browse/B2B-2165?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

B2B-2165 refactor to simpler interfaces within PDP 

---

apps/storefront/src/pages/QuoteDetail/index.tsx

Jira: [B2B-2160](https://bigcommercecloud.atlassian.net/browse/B2B-2160)
- Move data fetching and reshaping logic into useData to move it away from presentation code
- Manual 
[B2B-2160]: https://bigcommercecloud.atlassian.net/browse/B2B-2160?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

B2B-2160 move data fetching into useData within QuoteDetail

---

apps/storefront/src/pages/ShoppingLists/index.tsx

Jira: [B2B-2150](https://bigcommercecloud.atlassian.net/browse/B2B-2150)
- Move additional logic and fetching into the Page's `useData` hook
- Manual
[B2B-2150]: https://bigcommercecloud.atlassian.net/browse/B2B-2150?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

B2B-2150 - move more business logic and data fetching into useData within ShoppingLists

---

apps/storefront/src/pages/QuotesList/index.tsx

﻿﻿﻿### refactor(quote-list): extract getAvailableFilters to useData
Extract the getAvailableFilters method, remove some of the indirection
and further separate the b2b path from the b2c path.
Revert
Manual

refactor(quote-list): extract getQuotesList to useData

---

apps/storefront/src/pages/quote/components/Message.tsx

Jira: [B2B-2390](https://bigcommercecloud.atlassian.net/browse/B2B-2390)
Improving the padding left/right in the messaging input component in quote details. 
Revert PR
https://github.com/user-attachments/assets/4dae3652-7010-4a48-b295-8dddd053d594
[B2B-2390]: https://bigcommercecloud.atlassian.net/browse/B2B-2390?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(quotes): b2b-2390 fix padding in message input

---

apps/storefront/src/shared/routeList.ts
apps/storefront/src/utils/b3CheckPermissions/b2bPermissionPath.ts
apps/storefront/src/utils/b3CheckPermissions/base.ts
apps/storefront/src/utils/b3CheckPermissions/check.ts
apps/storefront/src/utils/b3CheckPermissions/config.ts

Jira: [B2B-2164](https://bigcommercecloud.atlassian.net/browse/B2B-2164)
Simplify the unnecessary complexity around permissions, rename a few variables and remove part of the indirection.
Revert
Mostly automated refactors/manual.
[B2B-2164]: https://bigcommercecloud.atlassian.net/browse/B2B-2164?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

refactor: simplify permissions logic

---

.circleci/config.yml
.husky/commit-msg
.husky/pre-commit
README.md
commit-validation.json
commitlint.config.js

Jira: [B2B-2596](https://bigcommercecloud.atlassian.net/browse/B2B-2596)
Using CircleCI to validate commit based on BC standards
Revert
CircleCI passed
When commit does not meet validation, failed:
https://github.com/bigcommerce/b2b-buyer-portal/pull/274
[B2B-2596]: https://bigcommercecloud.atlassian.net/browse/B2B-2596?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore(common): B2B-2596 add commit validation on CircleCI

---

apps/storefront/src/pages/Registered/RegisteredStep.tsx
apps/storefront/src/pages/Registered/index.tsx
commit-validation.json

Jira: [B2B-2166](https://bigcommercecloud.atlassian.net/browse/B2B-2166)
isStepOptional always sets the step `-1` as optional, that's not a valid step in the list of steps.
Revert
manual
[B2B-2166]: https://bigcommercecloud.atlassian.net/browse/B2B-2166?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

refactor(account): B2B-2166 Remove isStepOptional as it is not used

---

apps/storefront/src/pages/Login/LoginForm.tsx
apps/storefront/src/pages/Login/LoginPanel.tsx
apps/storefront/src/pages/Login/index.tsx
apps/storefront/src/pages/Login/useLogout.tsx

Jira: [B2B-2164](https://bigcommercecloud.atlassian.net/browse/B2B-2164)
- Extract the logout method from the login page
- Replace custom components/callbacks with standard mui components
Revert
[B2B-2164]: https://bigcommercecloud.atlassian.net/browse/B2B-2164?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

refactor: extract logout method from the Login Page

---

apps/storefront/src/components/B3LinkTipContent.tsx
apps/storefront/src/components/HeadlessController.tsx
apps/storefront/src/components/layout/B3MainHeader.tsx
apps/storefront/src/pages/Login/index.tsx
apps/storefront/src/pages/Login/useLogout.tsx
apps/storefront/src/pages/QuoteDraft/index.tsx
apps/storefront/src/pages/ShoppingListDetails/components/AddToShoppingList.tsx
apps/storefront/src/utils/b3CallbackManager.ts
apps/storefront/tests/utils/eventManager.test.ts
packages/hooks/index.d.ts
packages/hooks/useB2BCallback.ts

Jira: [B2B-2146](https://bigcommercecloud.atlassian.net/browse/B2B-2146)
Simplify `useB2BCallback` into a simple `dispatchEvent` method.
Revert
Manual/Unit
[B2B-2146]: https://bigcommercecloud.atlassian.net/browse/B2B-2146?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

refactor: simplify useB2BCallback into a simple wrapper method for dispatchEvent

---

apps/storefront/vite.config.ts

Jira: [B2B-2669](https://bigcommercecloud.atlassian.net/browse/B2B-2669)
Chrome complains of CORS issues when trying to use buyer portal in dev mode. Allow CORS.
Revert
[B2B-2669]: https://bigcommercecloud.atlassian.net/browse/B2B-2669?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(common): B2B-2669 Enable CORS in dev mode

---

apps/storefront/src/pages/Registered/index.tsx

Jira: [B2B-2146](https://bigcommercecloud.atlassian.net/browse/B2B-2146)
Fix rename issue caused by a rebase/merged into main.
Revert
typescript
[B2B-2146]: https://bigcommercecloud.atlassian.net/browse/B2B-2146?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(account): B2B-2146 Change `data` to `customer` to fix rebase issue

---

apps/storefront/package.json
apps/storefront/src/components/table/B3Table.tsx
apps/storefront/src/utils/graphqlDataConvert.ts
apps/storefront/tests/components/b3table/B3Table.test.tsx
packages/lang/locales/en.json
yarn.lock

Jira: [B2BCAT-3](https://bigcommercecloud.atlassian.net/browse/B2BCAT-3)
Update to the latest TS version. Mainly to try to fix a bug where deps. are typechecked even though skipLibCheck is set to true.
Also, newer version of TS is always better.
Revert
Build still passes
[B2BCAT-3]: https://bigcommercecloud.atlassian.net/browse/B2BCAT-3?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore(common): B2BCAT-3 Bump Typescript to the latest version

---

apps/storefront/src/pages/Address/components/AddressItemCard.tsx
apps/storefront/src/pages/Address/index.tsx

Jira: [B2B-2154](https://bigcommercecloud.atlassian.net/browse/B2B-2154)
Take some of the complexity out of the Card component, and reduce the coupling to the parent component.
Revert
manual
[B2B-2154]: https://bigcommercecloud.atlassian.net/browse/B2B-2154?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

refactor(addresses): B2B-2154 Simplify AddressItemCard interface

---

apps/storefront/src/pages/QuotesList/index.mobile.test.tsx

- Add missing mobile tests for the Quoting Listing page
- Revert
- New tests (no production code changed)

refactor(quotes): B2B-2149 add basic mobile tests to quotes listing page

---

apps/storefront/src/pages/AddressList/components/AddressForm.tsx

Jira: [B2B-2154](https://bigcommercecloud.atlassian.net/browse/B2B-2154)
Simplify the translation logic in AddressForm
Revert
manual
[B2B-2154]: https://bigcommercecloud.atlassian.net/browse/B2B-2154?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

refactor(addresses): B2B-2154 Simplify address fields translation logic in AddressForm

---

apps/storefront/.eslintrc.json
apps/storefront/src/components/HeadlessController/index.tsx
apps/storefront/src/pages/Dashboard/index.mobile.test.tsx
apps/storefront/src/pages/Dashboard/index.test.tsx
apps/storefront/src/pages/Dashboard/index.tsx
apps/storefront/src/pages/QuoteDetail/index.test.tsx
apps/storefront/src/pages/QuotesList/index.mobile.test.tsx
apps/storefront/src/pages/QuotesList/index.test.tsx
apps/storefront/src/pages/UserManagement/index.test.tsx
apps/storefront/src/shared/service/b2b/graphql/global.ts
apps/storefront/src/store/index.ts
apps/storefront/src/utils/masquerade.ts
apps/storefront/tests/storeStateBuilders/b2bFeaturesStateBuilder.ts
apps/storefront/tests/storeStateBuilders/index.ts
commit-validation.json

Jira: [B2BCAT-10](https://bigcommercecloud.atlassian.net/browse/B2BCAT-10)
Add test harness for the Dashboard page.
Revert
Mostly tests, the rest of the code is quite trivial.
[B2BCAT-10]: https://bigcommercecloud.atlassian.net/browse/B2BCAT-10?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

test(dashboard): B2BCAT-10 Add test harness for the Dashboard page

---

apps/storefront/src/pages/UserManagement/index.test.tsx
apps/storefront/src/shared/service/b2b/graphql/roleAndPermissions.ts
apps/storefront/src/shared/service/b2b/graphql/users.ts

- Add test for adding users within the Users Management page
- Revert
- New tests added (no user facing code changed)

refactor(user-management): B2BCAT-22 add tests for adding users in Users Management

---

apps/storefront/package.json
apps/storefront/src/pages/Dashboard/index.test.tsx
apps/storefront/src/pages/MyOrders/index.mobile.test.tsx
apps/storefront/src/pages/MyOrders/index.test.tsx
apps/storefront/src/pages/order/Order.tsx
apps/storefront/src/pages/order/config.ts
apps/storefront/src/shared/service/b2b/graphql/orders.ts
apps/storefront/src/store/selectors.ts
apps/storefront/tests/test-utils.tsx
yarn.lock

Jira: [B2BCAT-11](https://bigcommercecloud.atlassian.net/browse/B2BCAT-11)
- Add an initial pass of test harnesses for the MyOrders page.
- Bump MSW
Revert
Most of this PR is just testing.
[B2BCAT-11]: https://bigcommercecloud.atlassian.net/browse/B2BCAT-11?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

test(orders): B2BCAT-11 Add initial test harness for MyOrders

---

apps/storefront/src/pages/PDP/index.tsx

Jira: [B2B-2549](https://bigcommercecloud.atlassian.net/browse/B2B-2549)
Scrolling to top after adding a product to shopping list. 
Revert
https://github.com/user-attachments/assets/69a42b18-90f7-47e9-8fd1-4124292575a3
[B2B-2549]: https://bigcommercecloud.atlassian.net/browse/B2B-2549?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(catalyst): B2B-2549 fix scroll position on open pdp route

---

apps/storefront/src/pages/ShoppingListDetails/index.test.tsx
apps/storefront/src/shared/service/b2b/graphql/product.ts

Jira: [B2BCAT-17](https://bigcommercecloud.atlassian.net/browse/B2BCAT-17)
- Add missing graphql mock to Shopping List Details test
- Revert 
- New tests (no user facing code changed)
[B2BCAT-17]: https://bigcommercecloud.atlassian.net/browse/B2BCAT-17?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

refactor(quotes): B2BCAT-17 add missing graphql mock in shopping lists tests

---

apps/storefront/src/pages/UserManagement/index.tsx
apps/storefront/src/pages/UserManagement/table/B3NoData.tsx
apps/storefront/src/pages/UserManagement/table/B3PaginationTable.tsx
apps/storefront/src/pages/UserManagement/table/B3Table.tsx

**N.B.** This is a refactoring of production code, aimed at changing structure and _not_ behaviour 
- To try and tighten props and get a clearer understanding of the data the page needs:
- Copy over the full `table` component to the User Management page
- Inline all the hardcoded prop values and remove all the unused props and branches 
- Protected by existing tests
https://github.com/user-attachments/assets/e2dfa160-4a2e-47d4-97d5-735703eff9f9

User management B3PaginationTable refactor

---

apps/storefront/src/pages/QuotesList/index.mobile.test.tsx
apps/storefront/src/pages/QuotesList/index.test.tsx
apps/storefront/src/shared/service/b2b/graphql/quote.ts

- Add tests proving the special case of listing a draft quote
- Revert
- New tests, no user facing code changed

refactor(quotes): B2B-2149 add draft quote tests to quotes listing page

---

rfc/graphql-schema/b2b-full-schema.graphql

Jira: [B2BCAT-37](https://bigcommercecloud.atlassian.net/browse/B2BCAT-37)
Initial download of the whole B2B schema. Added as an rfc to start modifying it towards the end schema.
Documentation only
n/a
[B2BCAT-37]: https://bigcommercecloud.atlassian.net/browse/B2BCAT-37?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

docs(common): B2BCAT-37 Initial download of the full graphql schema from the b2b server

---

apps/storefront/__mocks__/react-router-dom.ts
apps/storefront/src/pages/OrderDetail/components/DetailPagination.tsx
apps/storefront/src/pages/OrderDetail/components/OrderAction.tsx
apps/storefront/src/pages/OrderDetail/index.test.tsx
apps/storefront/src/shared/global/context/config.ts
apps/storefront/src/shared/service/b2b/graphql/address.ts
apps/storefront/src/shared/service/b2b/graphql/orders.ts
apps/storefront/tests/test-utils.tsx

Jira: [B2BCAT-19](https://bigcommercecloud.atlassian.net/browse/B2BCAT-19)
This pass includes test for the desktop version of the OrderDetails for Personal Customers.
Revert
This PR is mostly testing. 
[B2BCAT-19]: https://bigcommercecloud.atlassian.net/browse/B2BCAT-19?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

test(orders): B2BCAT-19 First round of tests for the OrderDetail page

---

apps/storefront/src/components/HeadlessController/index.test.tsx
apps/storefront/src/shared/service/b2b/graphql/shoppingList.ts

Jira: [B2BCAT-38](https://bigcommercecloud.atlassian.net/browse/B2BCAT-38)
Initial tests for headless controller specifically getLists fn.
Revert
Test suite passes in the CI
[B2BCAT-38]: https://bigcommercecloud.atlassian.net/browse/B2BCAT-38?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

test(shopping-lists): B2BCAT-38 headless controller tests for sls

---

.circleci/config.yml
apps/storefront/vite.config.ts

Updating config yml to upload coverage reports
Revert 
WIP

fix(quotes): B2B-2811 adding coverage report

---

apps/storefront/src/main.ts

Pointing to micrapps cdn for staging env
Revert
WIP

feat(common): B2B-3029 using microapps cdn in staging env

---

config/deploy/after.sh
deployment/production-tier1.json

I'm updating our after.sh deployment file to start using BC CDN to test stores of the prod tier1 list first before pushing the change for the whole prod environment.
Revert 
WIP

feat(common): B2B-3031 using microapps cdn for tier 1

---

apps/storefront/src/main.ts
config/deploy/after.sh

I'm updating the cdn url for prod environment and making the required changes to the after script to deploy to all envs
Revert 
WIP

fix(common): B2B-3031 updating after script to deploy to all envs

---

apps/storefront/src/pages/QuickOrder/index.main.test.tsx
apps/storefront/src/pages/QuickOrder/index.quickpad.test.tsx
apps/storefront/src/pages/QuickOrder/utils.ts
apps/storefront/src/pages/ShoppingListDetails/components/ShoppingDetailFooter.tsx
apps/storefront/src/shared/service/b2b/graphql/global.ts
apps/storefront/src/shared/service/b2b/graphql/quickOrder.ts
apps/storefront/src/shared/service/bc/graphql/cart.ts
apps/storefront/src/utils/b3TriggerCartNumber.ts
apps/storefront/tests/test-utils.tsx
apps/storefront/vite.config.ts

🗒️ Ignore first 2 commits, they are part of:
- https://github.com/bigcommerce/b2b-buyer-portal/pull/403
Jira: [B2BCAT-18](https://bigcommercecloud.atlassian.net/browse/B2BCAT-18)
Initial test harness for QuickOrder and QuickOrderPad.
Revert
Most of this changes are test related, the rest are minor changes to adjust the types.
[B2BCAT-18]: https://bigcommercecloud.atlassian.net/browse/B2BCAT-18?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

test(quick-order): B2BCAT-18 First pass of the test harness

---

apps/storefront/src/pages/CompanyHierarchy/components/CompanyTableRowCard.tsx
apps/storefront/src/pages/CompanyHierarchy/components/TableTree.tsx
apps/storefront/src/pages/CompanyHierarchy/index.mobile.test.tsx
apps/storefront/src/pages/CompanyHierarchy/index.test.tsx
apps/storefront/src/shared/service/b2b/graphql/global.ts
packages/lang/locales/en.json

Jira: [B2BCAT-21](https://bigcommercecloud.atlassian.net/browse/B2BCAT-21)
- Add new tests for both the mobile and desktop views of Company Hierarchy
- Some aria-labels and roles added to make test selection easier
- Revert
- New tests
[B2BCAT-21]: https://bigcommercecloud.atlassian.net/browse/B2BCAT-21?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

refactor(company-hierarchy): B2BCAT-21 add test harness for Company Hierarchy

---

rfc/graphql-schema/additionalTypeDefs/byPage/companyHierarchy.ts
rfc/graphql-schema/additionalTypeDefs/index.ts
rfc/graphql-schema/openQuestions.md

Jira: [B2BCAT-62](https://bigcommercecloud.atlassian.net/browse/B2BCAT-62)
- Add a draft of the schema needed to drive the Company Hierarchy page
- Revert
- N/A, developer facing documentation only
[B2BCAT-62]: https://bigcommercecloud.atlassian.net/browse/B2BCAT-62?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

docs(dashboard): B2BCAT-62 draft of the Company Hierarchy Schema

---

apps/storefront/src/pages/AccountSetting/index.tsx

Jira: [B2B-2346](https://bigcommercecloud.atlassian.net/browse/B2B-2346)
Re-fetch the data instead of trigggering a page reload to refetch the data as the UI elements to be rendered don't change on update only the data inside them changes.
Revert this PR
https://github.com/user-attachments/assets/643e34e4-6a53-44f1-9f33-23cd9b5cb21e
https://github.com/user-attachments/assets/1080959a-9cbd-444b-85da-029927a1e92c
@bigcommerce/team-customers 
@bigcommerce/team-b2b 
[B2B-2346]: https://bigcommercecloud.atlassian.net/browse/B2B-2346?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(b2b): b2b-2346 reload data on account settings update instead of reloading page

---

apps/storefront/src/pages/ShoppingListDetails/index.test.tsx
apps/storefront/src/shared/service/b2b/graphql/shoppingList.ts

Jira: [B2BCAT-23](https://bigcommercecloud.atlassian.net/browse/B2BCAT-23)
- Add test for changing quantities
- Add test for updating product notes
- Revert
[B2BCAT-23]: https://bigcommercecloud.atlassian.net/browse/B2BCAT-23?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

refactor(shopping-lists): B2BCAT-23 add test for editing item notes and quantities

---

rfc/graphql-schema/additionalTypeDefs/byPage/addresses.ts
rfc/graphql-schema/additionalTypeDefs/byPage/shoppingLists.ts
rfc/graphql-schema/additionalTypeDefs/index.ts

Jira: [B2BCAT-5](https://bigcommercecloud.atlassian.net/browse/B2BCAT-5)
Add a draft schema for CompanyAddresses
Revert
n/a
[B2BCAT-5]: https://bigcommercecloud.atlassian.net/browse/B2BCAT-5?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

docs(addresses): B2BCAT-5 Add draft schema for CompanyAddress

---

apps/storefront/package.json
apps/storefront/src/pages/ForgotPassword/index.test.tsx
apps/storefront/src/pages/ForgotPassword/index.tsx
apps/storefront/src/pages/Invoice/InvoiceItemCard.tsx
apps/storefront/src/pages/Invoice/components/B3Pulldown.tsx
apps/storefront/src/pages/Invoice/components/InvoiceStatus.tsx
apps/storefront/src/pages/Invoice/components/triggerPdfDownload.tsx
apps/storefront/src/pages/Invoice/index.mobile.test.tsx
apps/storefront/src/pages/Invoice/index.test.tsx
apps/storefront/src/pages/Invoice/index.tsx
apps/storefront/src/pages/Invoice/utils/payment.ts
apps/storefront/src/pages/Invoice/utils/pdf.ts
apps/storefront/src/shared/service/b2b/graphql/invoice.ts
apps/storefront/src/utils/b3CheckPermissions/check.ts
apps/storefront/tests/headless.test.ts
apps/storefront/tests/setup-test-environment.ts
commit-validation.json
packages/lang/locales/en.json
yarn.lock

Jira: [JIRA_TOKEN](https://bigcommercecloud.atlassian.net/browse/JIRA_TOKEN)
Add test harness for InvoicesList
Add `vitest-location-mock`: JSDOM complains if the browser tries to navigate. This helper fixes
that and allows code to try and navigate away from the original url.
Revert
This is mostly tests, few minor tweaks in the UI, mostly roles.

test(invoices): B2BCAT-13 Add test harness for InvoicesList

---

apps/storefront/src/pages/Invoice/components/PaymentSuccess.tsx
apps/storefront/src/pages/Invoice/index.test.tsx
apps/storefront/src/shared/service/b2b/graphql/invoice.ts
apps/storefront/tests/test-utils.tsx

Jira: [B2BCAT-13](https://bigcommercecloud.atlassian.net/browse/B2BCAT-13)
- Add a couple of tests for receipt payment details and invoice details
- Add `key` in a couple of `[].map`
- Ensure `StringContainingAll` doesn't throw if something other than a string is passed.
Revert
This are mostly tests
[B2BCAT-13]: https://bigcommercecloud.atlassian.net/browse/B2BCAT-13?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

test(invoice): B2BCAT-13 Add test harnesses for invoiceId/receiptId

---

README.md

Jira: [B2B-3434](https://bigcommercecloud.atlassian.net/browse/B2B-3434)
Add information regarding releases
Revert
Not available
[B2B-3434]: https://bigcommercecloud.atlassian.net/browse/B2B-3434?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

doc(common): B2B-3434 Add release information to README

---

apps/storefront/src/pages/Dashboard/index.mobile.test.tsx
apps/storefront/src/pages/Dashboard/index.test.tsx
apps/storefront/src/pages/OrderDetail/components/OrderCheckboxProduct.tsx
apps/storefront/src/pages/OrderDetail/index.test.tsx
apps/storefront/src/pages/PDP/index.b2b.test.tsx
apps/storefront/src/pages/PDP/index.b2c.test.tsx
apps/storefront/src/pages/QuickOrder/index.main.test.tsx
apps/storefront/src/pages/QuickOrder/index.quickadd.test.tsx
apps/storefront/src/pages/QuickOrder/index.quickpad.test.tsx
apps/storefront/src/shared/service/b2b/graphql/orders.ts
apps/storefront/tests/setup-test-environment.ts
patches/@mui+material+5.18.0.patch

Jira: [B2BCAT-19](https://bigcommercecloud.atlassian.net/browse/B2BCAT-19)
These were overlooked on a previous PR. Adding test that prove these areas of the OrderDetails page.
Revert
This PR is mostly test files. CI should pass.
[B2BCAT-19]: https://bigcommercecloud.atlassian.net/browse/B2BCAT-19?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

test(orders): B2BCAT-19 Add tests for re-order & add-to-shopping-list in OrderDetails

---

rfc/graphql-schema/additionalTypeDefs/byPage/invoices.ts
rfc/graphql-schema/additionalTypeDefs/byPage/orders.ts

Jira: [B2BCAT-67](https://bigcommercecloud.atlassian.net/browse/B2BCAT-67)
Add some required fields to cater for the OrderDetails page.
Revert 🤷 
This PR is documentation.
[B2BCAT-67]: https://bigcommercecloud.atlassian.net/browse/B2BCAT-67?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

docs(orders): B2BCAT-67 Add required fields for OrderDetails

---

rfc/graphql-schema/additionalTypeDefs/byPage/orders.ts
rfc/graphql-schema/additionalTypeDefs/byPage/shoppingListDetails.ts
rfc/graphql-schema/additionalTypeDefs/byPage/shoppingLists.ts
rfc/graphql-schema/additionalTypeDefs/index.ts

Jira: [B2BCAT-89](https://bigcommercecloud.atlassian.net/browse/B2BCAT-89)
Add `ShoppingListDetails` schema definition.
Revert
This is documentation.
[B2BCAT-89]: https://bigcommercecloud.atlassian.net/browse/B2BCAT-89?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

docs(shopping-lists): B2BCAT-89 Add ShoppingListDetails schema

---

rfc/graphql-schema/additionalTypeDefs/byPage/quickOrder.ts
rfc/graphql-schema/additionalTypeDefs/index.ts

Jira: [B2BCAT-68](https://bigcommercecloud.atlassian.net/browse/B2BCAT-68)
Draft schema for Quick Order
Revert
NA, draft schema only
[B2BCAT-68]: https://bigcommercecloud.atlassian.net/browse/B2BCAT-68?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(quick-order): B2BCAT-68 quickorder schema

---

rfc/graphql-schema/additionalTypeDefs/byPage/quoteDetails.ts
rfc/graphql-schema/additionalTypeDefs/index.ts

Jira: [B2BCAT-69](https://bigcommercecloud.atlassian.net/browse/B2BCAT-69)
- Draft schema to support the queries and mutations of the Quote Details page
- Revert
- N/A - purely a draft schema
[B2BCAT-69]: https://bigcommercecloud.atlassian.net/browse/B2BCAT-69?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

docs(quotes): B2BCAT-70 Add schemas for QuoteDetails

---

rfc/graphql-schema/additionalTypeDefs/byPage/addToShoppingList.ts
rfc/graphql-schema/additionalTypeDefs/index.ts

Jira: [B2BCAT-64](https://bigcommercecloud.atlassian.net/browse/B2BCAT-64)
Add to shopping list draft schema, just docs
NA
NA
[B2BCAT-64]: https://bigcommercecloud.atlassian.net/browse/B2BCAT-64?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

docs(shopping-lists): B2BCAT-64 add to shopping list draft schema

---

apps/storefront/src/pages/QuoteDraft/index.test.tsx
apps/storefront/src/pages/quote/components/QuoteTable.tsx

Jira: [B2B-3325](https://bigcommercecloud.atlassian.net/browse/B2B-3325)
This PR hides the stock warning messages in the product table when the backordering feature flag is enabled. These changes are required because the frontend validation checks do not support backordering. 
These checks are not required when the feature flag is enabled because the backend handles them.
Before (inaccurate warning message):
https://github.com/user-attachments/assets/13cbf19b-421c-4026-a31f-81d260a6d04b
After:
https://github.com/user-attachments/assets/a89d7bae-a08d-4ecf-a50d-99d77d834288
[B2B-3325]: https://bigcommercecloud.atlassian.net/browse/B2B-3325?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(quotes): B2B-3325 Hide error messages in product table when backordering is enabled

---

apps/storefront/src/App.tsx
apps/storefront/src/constants/index.ts
apps/storefront/src/pages/Registered/index.tsx
apps/storefront/src/shared/routes/index.tsx
commit-validation.json

Jira: [B2B-3501](https://bigcommercecloud.atlassian.net/browse/B2B-3501)
This commit redirects the user back to checkout when the `redirectTo=checkout` param is present.
This enhances the flow where a user click "create account" in checkout, as it takes them back to where they were after registration.
As part of this same change, we've tighten the detection of certain scenarios, making sure we avoid certain false~positives when detecting checkout/change_password/etc.
Revert
WIP
[B2B-3501]: https://bigcommercecloud.atlassian.net/browse/B2B-3501?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(register): B2B-3501 Honour `?redirectTo=checkout` after registration

---

apps/storefront/src/pages/QuickOrder/components/QuickAdd.tsx
apps/storefront/src/pages/QuickOrder/index.main.test.tsx
apps/storefront/src/pages/QuickOrder/utils.ts

Jira: [B2B-3345](https://bigcommercecloud.atlassian.net/browse/B2B-3345)
enable quick add, add to cart for backordering
Revert this PR
https://github.com/user-attachments/assets/13b03c1b-a9b6-4582-bf28-4dab0c83cded
[B2B-3345]: https://bigcommercecloud.atlassian.net/browse/B2B-3345?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(quick-order): B2B-3345 enable backorder on quick add to cart
