bigcommerce/b2b-buyer-portal

- .github/CODEOWNERS
- update `CODEOWNERS` file to use the bigcommerce org team
- currently github says the CODEOWNERS file is invalid.
Revert PR
ping @bigcommerce/b2b-buyer-portal
> fix: update CODEOWNERs to point to bigcommerce team

- README.md
Write a description of the changes you're making here, and decisions that you made
along the way. Provide enough context that the reviewer(s) can understand your
changes, and the intent behind them. For more details refer to [contributing guideline](https://github.com/bigcommerce/bigcommerce/blob/master/CONTRIBUTING.md#what)
Describe the underlying driver or intent behind this change. Provide some context
on why it's needed or what is the intended use. For more details refer to [contributing guideline](https://github.com/bigcommerce/bigcommerce/blob/master/CONTRIBUTING.md#why)
Explain what you did to test and ensure that these changes work the way you expect.
You must provide evidence in the form of unit tests, screenshots, logs, API
payloads or other output to show the expected …
> updates header in readme

- apps/storefront/src/types/.prettierrc
- apps/storefront/src/utils/.prettierrc
Remove unused prettierrc files.
These are no longer necessary, the configuration is set in package.json
n/a
Revert
> chore: remove unused .prettierrc

- apps/storefront/src/components/loading/Loading.tsx
- apps/storefront/src/components/spin/B3Sping.tsx
- add role=progressbar to loading indicators / text
- allows our e2e test to properly wait
- follows the [accessibility standards](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/progressbar_role)
Revert
> fix: add role=progressbar for loading indicators

- apps/storefront/src/shared/service/bc/api/cart.ts
- apps/storefront/src/shared/service/request/b3Fetch.ts
- apps/storefront/src/shared/service/request/fetch.ts
Move logic that is specific to a particular type of endpoint outside the generic fetch function.
This type of coupling is messy, making it hard to reason about the way fetch works.
Moving this out makes each execution path easier to follow.
When I learn how to run the functional tests, I will.
For the most part, this is just copy/paste.
Revert.
> refactor(request): move api specific logic outside the fetch method

- apps/storefront/src/components/B3DropDown.tsx
- apps/storefront/src/components/button/CustomButton.tsx
- apps/storefront/src/components/upload/BulkUploadTable.tsx
- apps/storefront/src/pages/dashboard/Dashboard.tsx
- apps/storefront/src/pages/invoice/components/B3Pulldown.tsx
- apps/storefront/src/pages/orderDetail/components/OrderAction.tsx
- apps/storefront/src/pages/quickorder/components/QuickOrderFooter.tsx
- apps/storefront/src/pages/shoppingListDetails/components/ShoppingDetailFooter.tsx
Replace `useState` with `useRef` when defining popover/dropdown targets.
Using useState, removes the target upon closing, which impedes animations. This is also not the best practice in terms of storing/passing elements around.
https://github.com/bigcommerce/b2b-buyer-portal/assets/4542735/b851b071-1b31-4552-acb4-fa2b56c0c994
Revert this PR
> refactor: use useRef instead of useState to define dropdown/popover targets

- package.json
- turbo.json
- yarn.lock
Bump turbo to v2
Keeping deps up to date.
self explanatory in the PR
Revert this PR
> chore: bump turbo@2

- apps/storefront/src/pages/Login/LoginPanel.tsx
- apps/storefront/src/pages/Login/component/LoginWidget.tsx
- apps/storefront/src/pages/Login/config.ts
- apps/storefront/src/pages/Login/index.tsx
Remove unnecessary prop, if we don't want to show the component, we should just not render it.
Revert
TS + Manual checks
> refactor: remove unnecessary isVisible from the LoginWidget component

- apps/storefront/src/components/B3Card.tsx
- apps/storefront/src/components/HeadlessController.tsx
- apps/storefront/src/components/RegisteredCloseButton.tsx
- apps/storefront/src/components/extraTip/CheckoutTip.tsx
- apps/storefront/src/components/layout/B3RenderRouter.tsx
- apps/storefront/src/components/outSideComponents/B3HoverButton.tsx
- apps/storefront/src/components/outSideComponents/B3MasquradeGobalTip.tsx
- apps/storefront/src/hooks/dom/useOpenPDP.ts
- apps/storefront/src/hooks/dom/utils.ts
- apps/storefront/src/pages/Dashboard/index.tsx
- apps/storefront/src/pages/ForgotPassword/index.tsx
- apps/storefront/src/pages/Login/index.tsx
- apps/storefront/src/pages/PDP/index.tsx
- apps/storefront/src/pages/PageProps.ts
- apps/storefront/src/pages/QuoteDraft/index.tsx
- apps/storefront/src/pages/Registered/index.tsx
- apps/storefront/src/pages/RegisteredBCToB2B/index.tsx
- apps/storefront/src/pages/SetOpenPage.tsx
- apps/storefront/src/pages/ShoppingListDetails/components/ShoppingDetailHeader.tsx
- apps/storefront/src/pages/ShoppingListDetails/index.tsx
- apps/storefront/src/shared/routes/index.tsx
We are currently repeating the same definition on each page, and type checking the list of routes is a bit more complex than it needs to be.
This introduces a type for `PageProps` that all pages can conform to and can be used to type the RouteItem.
Revert
typescript
> refactor: add a PageProps interface to simplify the definition of the standard props for a page

- apps/storefront/src/hooks/useB3AppOpen.ts
- packages/global-b3/index.ts
Jira: [BUN-2601](https://bigc-b2b.atlassian.net/browse/BUN-2601)
Improve Buyer Portal compatibility for Beatify Theme
* When clicking the account icon, in most cases, you cannot enter the buyer portal page, but stay on a blank page.
Reason: The theme code is not compatible with the class name or other specific identifiers corresponding to the icon; this pr adds specific identifiers in the code to be compatible with the theme.
undo this pr
https://github.com/bigcommerce/b2b-buyer-portal/assets/80307788/a769583d-d460-4173-bfdf-36cb44ef727a
> feat: compatible with beautify theme

- apps/storefront/src/pages/Login/LoginForm.tsx
- apps/storefront/src/pages/Login/LoginPanel.tsx
- apps/storefront/src/pages/Login/index.tsx
- apps/storefront/src/shared/service/b2b/graphql/register.ts
This commit extracts some of the logic in the login outside of it and simplifies the syntax a bit.
Also simplifies the creation and use of `loginInfo`, ensuring it is always defined.
Revert
Most of the refactor here is automated.
Page still loads fine:
> refactor: simplify login page (Step 1)

- apps/storefront/src/pages/ShoppingListDetails/index.tsx
- apps/storefront/src/pages/ShoppingLists/AddEditShoppingLists.tsx
- apps/storefront/src/shared/service/b2b/graphql/shoppingList.ts
- apps/storefront/src/utils/b3ShoppingList/b3ShoppingList.ts
Jira: [BUN-2621](https://bigcommercecloud.atlassian.net/browse/BUN-2621)
**Current issues:**
description is not escaped, graphql reports an error, description needs to be escaped
When we use strings in GraphQL queries or mutations, if the string contains special characters (such as newlines, double quotes, etc.), these characters may be mistaken as part of the syntax, resulting in parsing errors. For example, unescaped newlines can break the structure of the query and prevent it from parsing correctly
If we use newlines directly in the query, it will cause an error
mutation { updateDescription(description: "test\n") }
This causes parsing errors because newlines are mistaken for part of the syntax
To avoid this we need to use escape characters:
mutation { updateDescription(description: …
> fix: shopping list description bun2621

- apps/storefront/src/store/slices/company.ts
Jira: [BUN-2637](https://bigc-b2b.atlassian.net/browse/BUN-2637)
When the user is guest, customerGroupId should be 0, not 1,
causing calculated_price to obtain an incorrect price
undo pr
https://github.com/bigcommerce/b2b-buyer-portal/assets/80307788/b797a4b4-e27f-4e3c-aa75-db2b9c785623
> fix: set guest customerGroupId is 0

- apps/storefront/src/components/layout/B3Layout.tsx
- apps/storefront/src/components/layout/B3Logo.tsx
- apps/storefront/src/components/layout/B3MobileLayout.tsx
Jira: [BUN-1338](https://bigc-b2b.atlassian.net/browse/BUN-1338)
Issue: The Buyer Portal seems to be cropping the logo. It doesn’t look very good. We should adjust to fix most logo dimensions 
desk: 200x65 px
mob: 140x40 px
undo pr
desk:
mob:
> fix: bun1338 Add BigCommerce Requirements for store logos added in B2BE

- apps/storefront/src/components/layout/B3StatusNotification.tsx
- apps/storefront/src/constants/index.ts
- packages/lang/locales/en.json
Jira: [BUN-2764](https://bigc-b2b.atlassian.net/browse/BUN-2764)
I'm adding variables to translate notifications related to the status of new accounts. Right now there's no way to translate those notifications.
Revert
> fix: adding variables for translation of notifications

- apps/storefront/src/components/layout/B3Nav.tsx
- apps/storefront/src/utils/b3Storage.ts
Jira: [BUN-2749](https://bigc-b2b.atlassian.net/browse/BUN-2749)
I added back a variable to the session storage to keep the value of the route in the nav clicked before seeing the orderDetail. In the routes we have "My Orders" and "Company orders" and both re routes to page orderDetail when users clicks for a specific order, so they are both displayed as selected when in orderDetail page. By having saved the value from the path we clicked we can add styles only to one of those routes.
Revert
> fix: saving order path previous order detail

- README.md
Jira: [BUN-2802](https://bigc-b2b.atlassian.net/browse/BUN-2802)
Remove email from README as it is not a valid monitored email.
Revert
Not applicable
> fix: remove invalid email from readme

- apps/storefront/src/pages/Invoice/components/InvoiceFooter.tsx
- apps/storefront/src/pages/Invoice/index.tsx
- apps/storefront/src/types/invoice.ts
Jira: [SUP-1866](https://bigc-b2b.atlassian.net/browse/SUP-1866)
Due to rounding, the data is biased. So when the back end verifies based on the front end data, the value does not match, resulting in an error.
Modified to: When calling the invoice payment interface, the value is not rounded.
undo pr
> fix: fix invoice pay issue sup-1866

- apps/storefront/src/components/form/B3ControlAutocomplete.tsx
- apps/storefront/src/shared/service/b2b/graphql/roleAndPermissions.ts
Jira: [BUN-2871](https://bigc-b2b.atlassian.net/browse/BUN-2871)
remove the companyId parameter
It is no longer necessary。
API changed companyId parameter to optional;
Ticket BUN-2871, requirement, frontend removed companyId field.
undo pr
> fix: remove the companyId parameter

- apps/storefront/src/hooks/useB3AppOpen.ts
Jira: [BUN-2841](https://bigc-b2b.atlassian.net/browse/BUN-2841)
The passwordless login link email is not being sent correctly. Instead, it redirects the user to the Buyer Portal account registration.  Because the Buyer Portal has changed the link to jump to other
The solution:
Buyer Portal only needs to change the login and registration links
undo pr
https://github.com/user-attachments/assets/8a6bed75-029e-430b-8f46-06b2d3f64c91
> fix: checkout link open register page instead of sending mail

- packages/lang/locales/en.json
Issue - 
purchasedProducts.quickOrderPad.insufficientStockSku showing as msg when item not in stock
Result 
- It should be display translate msg
> fix: update translation variable

- apps/storefront/src/pages/Invoice/components/InvoiceFooter.tsx
- apps/storefront/src/pages/Invoice/index.tsx
- apps/storefront/src/types/invoice.ts
Reverts bigcommerce/b2b-buyer-portal#100
Jira: [B2B-1290](https://bigcommercecloud.atlassian.net/browse/B2B-1290)
Jira: [SUP-1866](https://bigcommercecloud.atlassian.net/browse/SUP-1866)
SUP-1866:
Due to rounding, the data is biased. So when the back end verifies based on the front end data, the value does not match, resulting in an error.
Modified to: When calling the invoice payment interface, the value is not rounded.
B2B-1290:
SUP-1866 caused the problem of B2B-1290, here the value entered in the input box will be compatible
undo pr
SUP-1866：
B2B-1290:
[B2B-1290]: https://bigcommercecloud.atlassian.net/browse/B2B-1290?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[SUP-1866]: https://bigcommercecloud.atlassian.net/browse/SUP-1866?atlOrigin= …
> Revert "fix: fix invoice pay issue sup-1866"

- apps/storefront/src/App.tsx
Jira: [B2B-1061](https://bigcommercecloud.atlassian.net/browse/B2B-1061)
refresh the flicker that appears in the load,
Because when the page is not loaded, the load mask is closed, and only the code needs to be deleted.
undo pr
https://github.com/user-attachments/assets/12df00b1-408a-4fb1-a8cf-4034417afa21
[B2B-1061]: https://bigcommercecloud.atlassian.net/browse/B2B-1061?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: refresh the flicker that appears in the load

- apps/storefront/src/utils/b3Login.ts
Jira: [B2B-1036](https://bigcommercecloud.atlassian.net/browse/B2B-1036)
loginLandingLocation login issues
When the loginLandingLocation option in the app login page settings is set to The storefront, a login redirect error occurs.
undo pr
https://github.com/user-attachments/assets/452b2459-7004-4510-aa70-556dd4e5ed72
[B2B-1036]: https://bigcommercecloud.atlassian.net/browse/B2B-1036?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: loginLandingLocation login issues

- apps/storefront/src/components/HeadlessController.tsx
- apps/storefront/src/index.d.ts
Jira: [B2B-1255](https://bigcommercecloud.atlassian.net/browse/B2B-1255)
Add cart util functions in order to help sync process in headless channels, this way they can have cart id in both sides
Undo this PR
https://github.com/user-attachments/assets/d522032a-6bab-4d74-bcdd-4a1396d7387a
[B2B-1255]: https://bigcommercecloud.atlassian.net/browse/B2B-1255?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: add cart sync util functions

- apps/storefront/src/App.tsx
- apps/storefront/src/pages/Login/index.tsx
Jira: [B2B-1061](https://bigcommercecloud.atlassian.net/browse/B2B-1061)
buyer portal When the browser refreshes or logs in to the theme page (cdn cache is not available), the buyer portal page flashes
**Buyer portal interface flash status**
Solution:
Exclude the checkout page and close redundant showPageMask(false) to solve the flash problem
**The checkout page does not trigger the mask**
Solution:
Method 1: After logging in to checkout, specify the path window.location.href = CHECKOUT_URL
Method 2: Make a separate checkout page judgment and close the mask
Both methods are compatible.
undo pr
https://github.com/user-attachments/assets/9330cf4c-77ee-4b93-9c6a-af95bebb2d0c
https://github.com/user-attachments/assets/3b9a0f08-4b04-4597-85a1-51d270cc8f6b
@LeoChowChina  @bc-micah @bc-victor …
> fix: resolve the problem that the buyer portal page flashes

- apps/storefront/src/hooks/dom/useMyQuote.ts
- apps/storefront/src/hooks/dom/utils.ts
- apps/storefront/src/pages/QuoteDraft/index.tsx
- apps/storefront/src/pages/quote/components/QuoteTable.tsx
- apps/storefront/src/utils/b3Product/b3Product.ts
- packages/lang/locales/en.json
Jira: [B2B-1316](https://bigcommercecloud.atlassian.net/browse/B2B-1316)
judge quote product oos
The judgment is made according to the setting item [Quote non-purchasable and out of stock products] in app -> settings -> quote.
When this function is turned off, it is not allowed to submit quotes for products that are out of stock or cannot be purchased.
undo pr
https://github.com/user-attachments/assets/9c72c070-b655-4f69-aa77-6f66b73a7ef5
[B2B-1316]: https://bigcommercecloud.atlassian.net/browse/B2B-1316?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: judge quote product oos

- apps/storefront/src/pages/PDP/index.tsx
Jira: [B2B-1447](https://bigcommercecloud.atlassian.net/browse/B2B-1447)
Fixing a bug where empty options would break the add product to shopping list callback. Adding support to choose a default variant id if no sku is supplied
Rolled out via ci/ revert
[B2B-1447]: https://bigcommercecloud.atlassian.net/browse/B2B-1447?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: empty options and default variant support for shopping list

- apps/storefront/src/components/HeadlessController.tsx
Jira: [B2B-1447](https://bigcommercecloud.atlassian.net/browse/B2B-1447)
Fixing a bug where the superAdminCompanies query would fail as the sortBy parameter is incorrect.
Rolled out via ci/ revert
[B2B-1447]: https://bigcommercecloud.atlassian.net/browse/B2B-1447?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: fixing superAdminCompany query in getMasquerade util

- apps/storefront/src/shared/service/b2b/api/register.ts
Jira: [B2B-1391](https://bigcommercecloud.atlassian.net/browse/B2B-1391)
Add channel id to payload to validate company extra fields to support translations
Undo this PR
[B2B-1391]: https://bigcommercecloud.atlassian.net/browse/B2B-1391?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: send channel id when validate company extrafields

- apps/storefront/vite.config.ts
Jira: [B2B-1506](https://bigcommercecloud.atlassian.net/browse/B2B-1506)
Fix bug by putting all MUI dependencies in one package
Undo this PR
[B2B-1506]: https://bigcommercecloud.atlassian.net/browse/B2B-1506?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: create manual chunk for mui with all dependencies

- apps/storefront/src/App.tsx
- apps/storefront/src/pages/Login/index.tsx
- apps/storefront/src/shared/service/b2b/graphql/register.ts
- apps/storefront/src/utils/loginInfo.ts
Jira: [B2B-1503](https://bigcommercecloud.atlassian.net/browse/B2B-1503)
Fix for a reported bug about users are not able to use routes through `b2b.utils.openPage` function, this includes:
- Use new query `customerInfo` to retrieve customer info
- Move logic to save permissions from login form view to getCompanyUserInfo function
- Remove `getCompanyUserInfo` where is not necessary
Undo this PR
https://github.com/user-attachments/assets/c0299069-20fa-4750-8af8-cafc45f826cf
https://github.com/user-attachments/assets/e735301b-8ac6-45d6-b905-cb714e9e6917
https://github.com/user-attachments/assets/df16b08a-0d60-456b-b061-65c0de3b3ce4
https://github.com/user-attachments/assets/b2d24e7c-2b88-46c0-902e-6a859c057097
https://github.com/user-attachments/assets/29e88284-71a1-48a3-ae74-b9b57d4d60fd …
> fix: set permissions consumed from new query

- apps/storefront/package.json
- apps/storefront/vite.config.ts
- package.json
- turbo.json
Jira: [B2B-1009](https://bigcommercecloud.atlassian.net/browse/B2B-1009)
Fix for deployment process to tier1
Undo this PR
[B2B-1009]: https://bigcommercecloud.atlassian.net/browse/B2B-1009?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: deploy headless.js file for tier1 environment

- .github/workflows/deploy-production-tier1-only.yml
- .github/workflows/deploy-production.yml
- .github/workflows/deploy-staging.yml
- .github/workflows/deploy.yml
Jira: [B2B-1585](https://bigcommercecloud.atlassian.net/browse/B2B-1585)
Add support for build command independent from environment in deployment workflow
Revert this PR 
NA
[B2B-1585]: https://bigcommercecloud.atlassian.net/browse/B2B-1585?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(b2b-1585): support for build command in deployment workflow

- apps/storefront/package.json
- apps/storefront/src/buyerPortal.ts
- package.json
- turbo.json
Jira: [B2B-1585](https://bigcommercecloud.atlassian.net/browse/B2B-1585)
- Add `tier1` mode in build commands
Revert
[Action running this branch](https://github.com/bigcommerce/b2b-buyer-portal/actions/runs/11584884119)
[B2B-1585]: https://bigcommercecloud.atlassian.net/browse/B2B-1585?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: add `tier1` mode in build commands

- apps/storefront/vite.config.ts
Jira: [B2B-1534](https://bigcommercecloud.atlassian.net/browse/B2B-1534)
Added config to generate sourcemaps on build
Undo this PR
[B2B-1534]: https://bigcommercecloud.atlassian.net/browse/B2B-1534?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: sourcemap generation on build

- apps/storefront/src/pages/Login/config.ts
- apps/storefront/src/pages/Login/index.tsx
Jira: [B2B-1559](https://bigcommercecloud.atlassian.net/browse/B2B-1559)
Headless checkout login api call needs to show error message properly to the user when the request to login /internalapi/checkout/* fails.
revert
[B2B-1559]: https://bigcommercecloud.atlassian.net/browse/B2B-1559?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: handling password reset error on login

- apps/storefront/src/components/HeadlessController.tsx
- apps/storefront/src/components/outSideComponents/B3MasquradeGobalTip.tsx
- apps/storefront/src/pages/Dashboard/index.tsx
- apps/storefront/src/pages/Login/index.tsx
- apps/storefront/src/shared/service/b2b/graphql/global.ts
- apps/storefront/src/types/gql/fragment-masking.ts
- apps/storefront/src/types/gql/gql.ts
- apps/storefront/src/types/gql/graphql.ts
- apps/storefront/src/utils/masquerade.ts
Jira: [B2B-1547](https://bigcommercecloud.atlassian.net/browse/B2B-1547)
We have a production bug in the masquerade operation. The backend team is starting to read the userId from the login token instead of exposing it in the mutation use to start/end masquerading.
I'm deleting the userId since the graphql schema is changing and also I'm adding the updated types generated based on the schemas.
Revert PR
[B2B-1547]: https://bigcommercecloud.atlassian.net/browse/B2B-1547?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: updating start and end masquerading mutations

- .circleci/config.yml
Jira: [INFRA-18574](https://bigcommercecloud.atlassian.net/browse/infra-18574)
Builds the application with Circle CI. This is required for a second type of deployment we're pursuing for this application.
Rollout will be done by internal deployment and verifying the application exists in the expected places.
Rollback is as simple as removing the Circle CI config, and turning off builds in CCI.
We can see the artifact uploaded to the GCS bucket here
[INFRA-18574]: https://bigcommercecloud.atlassian.net/browse/INFRA-18574?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: infra-18574: Add Circle CI builds

- apps/storefront/src/shared/service/request/b3Fetch.ts
Jira: [B2B-1581](https://bigcommercecloud.atlassian.net/browse/B2B-1581)
fix: disabling expired session redirect if the buyer portal is not open
Revert
[B2B-1581]: https://bigcommercecloud.atlassian.net/browse/B2B-1581?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: disabling expired session redirect

- apps/storefront/src/shared/service/b2b/graphql/register.ts
Jira: [B2B-1632](https://bigcommercecloud.atlassian.net/browse/B2B-1632)
Change `companyUserInfo` to `userLoginState` graphql query in order to improve security
Revert PR
[B2B-1632]: https://bigcommercecloud.atlassian.net/browse/B2B-1632?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: migrate from `companyUserInfo` to `userLoginState` graphql query

- apps/storefront/src/shared/service/b2b/graphql/login.ts
- apps/storefront/src/utils/loginInfo.ts
Jira: [NA](https://bigcommercecloud.atlassian.net/browse/NA)
Add validation to request only `bcGraphqlToken` in `bigcommerce` platforms
Revert
> fix: validate platform before request graphql token

- apps/storefront/src/shared/service/b2b/graphql/login.ts
Jira: [B2B-1684](https://bigcommercecloud.atlassian.net/browse/B2B-1684)
Compatible with type inconsistencies that occur in server deployments
> `src/utils/loginInfo.ts(117,31): error TS2345: Argument of type '{ storeHash: string; channel_id: number; expires_at: number; allowed_cors_origins: Location[]; }' is not assignable to parameter of type 'Partial<ApiTokenConfig>'.
> 10:44:52 AM: storefront:build:   Types of property 'allowed_cors_origins' are incompatible.
> 10:44:52 AM: storefront:build:     Type 'Location[]' is not assignable to type 'string[]'.
> 10:44:52 AM: storefront:build:       Type 'Location' is not assignable to type 'string'.`
undo pr
node: 18.18.0
node: 20.17.0
[B2B-1684]: https://bigcommercecloud.atlassian.net/browse/B2B-1684?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMD …
> fix: allowed_cors_origins Type definition

- apps/storefront/src/pages/CompanyHierarchy/components/TableTree.tsx
- packages/lang/locales/en.json
Jira: [B2B-1758](https://bigcommercecloud.atlassian.net/browse/B2B-1758)
Jira: [B2B-1808](https://bigcommercecloud.atlassian.net/browse/B2B-1808)
1758: Allow merchant customize every string of text displayed in buyer portal for Account Hierarchy
1808: UI copy updates for Account Hierarchy features on both CP and Buyer Portal
undo pr
[B2B-1758]: https://bigcommercecloud.atlassian.net/browse/B2B-1758?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[B2B-1808]: https://bigcommercecloud.atlassian.net/browse/B2B-1808?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: translation and change tips

- apps/storefront/src/shared/service/bc/api/login.ts
- apps/storefront/src/utils/loginInfo.ts
Jira: [NA](https://bigcommercecloud.atlassian.net/browse/NA)
Move currentCustomerJWT?.includes('errors') inside `getCurrentCustomerJWT` function, that way we avoid `console.error` an expected message
Revert this PR
> fix: validate errors inside getCurrentCustomerJWT

- apps/storefront/src/pages/AccountSetting/index.tsx
Jira: [B2B-1663](https://bigcommercecloud.atlassian.net/browse/B2B-1663)
accountSetting save requires that the companyId be a number
undo pr
https://github.com/user-attachments/assets/c987679b-3a6c-4327-879e-0a2854451d6f
[B2B-1663]: https://bigcommercecloud.atlassian.net/browse/B2B-1663?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: accountSetting save requires that the companyId be a number

- README.md
Jira: [B2B-1219](https://bigcommercecloud.atlassian.net/browse/B2B-1219)
I'm deleting the reference to an incorrect email in the readme to avoid confuse merchants
Revert
N/A
[B2B-1219]: https://bigcommercecloud.atlassian.net/browse/B2B-1219?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: deleting incorrect email from readme

- .cspell.json
- apps/storefront/src/components/HeadlessController.tsx
- apps/storefront/src/index.d.ts
Jira: [B2B-1903](https://bigcommercecloud.atlassian.net/browse/B2B-1903)
B2B logout for the headless controller. To be used in Catalyst sign out action.
Revert
https://github.com/bigcommerce/catalyst/pull/1744
[B2B-1903]: https://bigcommercecloud.atlassian.net/browse/B2B-1903?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: headless logout

- .github/workflows/deploy-staging.yml
Jira: [B2B-1943](https://bigcommercecloud.atlassian.net/browse/B2B-1943)
Improving deployment workflows to following state:
* Release to production just with manual trigger ( this is the current status)
* Tier 1 deployment , just with manual trigger. I want to change this for 2 reasons:
More control over Tier 1 content
API changes are not available in Tier 1 until we deploy it to production
* Staging  deployment triggered by merge operation to main and manual trigger
It will help us to have a more stable staging environment
Revert PR
NA
[B2B-1943]: https://bigcommercecloud.atlassian.net/browse/B2B-1943?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(b2b-1943): improved deployment to staging

- .cspell.json
- apps/storefront/src/hooks/dom/useRegisteredbctob2b.ts
- apps/storefront/src/pages/Login/index.tsx
- apps/storefront/src/shared/routes/index.tsx
- apps/storefront/src/shared/service/bc/graphql/user.ts
- apps/storefront/src/utils/b2bVerifyBcLoginStatus.ts
- apps/storefront/src/utils/b3logout.ts
Jira: [B2B-1549](https://bigcommercecloud.atlassian.net/browse/B2B-1549)
dual browser login makes the former log out normally
Optimize code: remove useless code and solve the problem of some interface errors during local runtime
undo pr
https://github.com/user-attachments/assets/a8eb5176-8d91-45ae-b351-deabf925d80c
[B2B-1549]: https://bigcommercecloud.atlassian.net/browse/B2B-1549?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: dual browser login makes the former log out normally

- apps/storefront/src/shared/service/b2b/api/translation.ts
- apps/storefront/src/shared/service/request/b3Fetch.ts
- apps/storefront/src/shared/service/request/base.ts
- apps/storefront/src/utils/b2bVerifyBcLoginStatus.ts
- apps/storefront/src/utils/headlessInitializer.ts
- apps/storefront/src/utils/loginInfo.ts
- apps/storefront/tests/headless.test.ts
Jira: [JIRA_TOKEN](https://bigcommercecloud.atlassian.net/browse/JIRA_TOKEN)
- `importNode` looked like it works, but the browser does not actually fetch the scripts or run the js.
- staging was not working properly because window.B3 value was being saved in global constant too early when using headless
We need to investigate this logic more to understand (this is already a revert)
Locally & planning to do in tier 1
> fix: headless.ts importNode to setAttribute & innerhtml

- apps/storefront/src/utils/b2bVerifyBcLoginStatus.ts
Jira: [B2B-2090](https://bigcommercecloud.atlassian.net/browse/B2B-2090)
#200 Introduced a new feature that verifies if a user is already authenticated in a different browser and broke catalyst login.
Revert
Buyer portal doesn't log you out automatically anymore
https://github.com/user-attachments/assets/e943f20a-69f7-4b03-aae9-fabaee9e2b93
[B2B-2090]: https://bigcommercecloud.atlassian.net/browse/B2B-2090?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: if a B2BToken is already set up, skip verification

- apps/storefront/src/components/HeadlessController.tsx
Jira: [B2B-1933](https://bigcommercecloud.atlassian.net/browse/B2B-1933)
Adding missing variable in useEffect dependency array
revert
tested in catalyst
[B2B-1933]: https://bigcommercecloud.atlassian.net/browse/B2B-1933?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: adding global state to the dependency array

- apps/storefront/src/components/HeadlessController.tsx
Jira: [B2B-1933](https://bigcommercecloud.atlassian.net/browse/B2B-1933)
Enabling usage of routes directly in the `openPage` function instead of only HeadlessRoutes keys.
Revert
Tested on Catalyst sf
[B2B-1933]: https://bigcommercecloud.atlassian.net/browse/B2B-1933?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: enable open page routes

- apps/storefront/src/utils/b3ClearCart.ts
Jira: [B2B-1909](https://bigcommercecloud.atlassian.net/browse/B2B-1909)
1. Cart Not Clearing After Navigating Away from Invoice Checkout
2. The special request based on "If the user quickly goes to invocie checkout and then immediately returns to the theme page" resulted in the cart not being deleted.
associated pr:  https://github.com/b3bc-external/b2b-checkout-app/pull/345
**The following logic is determined on the checkout screen**
- Determine whether other products have been added by judging the total amount.
total amount is returned via /api/v2/carts/{cartId} ==> cartType = 2
- Check whether a coupon is added to the current cart
Revert
https://github.com/user-attachments/assets/afaceeb8-4165-4ccb-bc7b-9bec1e9dff1b
[B2B-1909]: …
> fix: cart Clearing After Navigating Away from Invoice Checkout

- apps/storefront/src/pages/Login/index.tsx
Jira: [B2B-1966](https://bigcommercecloud.atlassian.net/browse/B2B-1966)
logout does not delete the cart, implement persistent cart in the Buyer Portal
Revert
https://github.com/user-attachments/assets/bd448565-af43-42c8-a8f8-0caa8075a9a8
[B2B-1966]: https://bigcommercecloud.atlassian.net/browse/B2B-1966?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: logout does not delete the cart, implement persistent cart

- .github/CODEOWNERS
Jira: [B2B-2135](https://bigcommercecloud.atlassian.net/browse/B2B-2135)
Add team customers to codeowners
Rollback
No testing needed
[B2B-2135]: https://bigcommercecloud.atlassian.net/browse/B2B-2135?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: b2b-2135: add team customers to codeowners

- apps/storefront/src/components/B3Dialog.tsx
- apps/storefront/src/pages/CompanyHierarchy/components/HierarchyDialog.tsx
- apps/storefront/src/pages/QuoteDraft/index.tsx
- apps/storefront/src/shared/service/b2b/graphql/shoppingList.ts
- apps/storefront/src/utils/b3CheckPermissions/check.ts
Tier 1 regression testing
super admin is compatible with company subsidiaries
undo pr
> fix: super admin is compatible with company subsidiaries

- apps/storefront/src/components/B3StoreContainer.tsx
- apps/storefront/src/pages/Address/index.tsx
- apps/storefront/src/pages/OrderDetail/index.tsx
- apps/storefront/src/pages/QuickOrder/components/QuickAdd.tsx
- apps/storefront/src/pages/QuotesList/index.tsx
- apps/storefront/src/pages/ShoppingListDetails/components/AddToShoppingList.tsx
- apps/storefront/src/pages/ShoppingListDetails/components/ChooseOptionsDialog.tsx
- apps/storefront/src/pages/ShoppingListDetails/components/QuickAdd.tsx
- apps/storefront/src/pages/ShoppingListDetails/components/SearchProduct.tsx
- apps/storefront/src/pages/ShoppingLists/index.tsx
- apps/storefront/src/pages/order/Order.tsx
- apps/storefront/src/pages/quote/components/AddToQuote.tsx
- apps/storefront/src/shared/service/request/b3Fetch.ts
- apps/storefront/src/utils/storefrontConfig.ts
Jira: [FE-418](https://bigcommercecloud.atlassian.net/browse/FE-418)
Move type definition to the fetch function. This is in preparation for stricter types.
Fix some typos, cspell complains otherwise.
Revert
n/a
[FE-418]: https://bigcommercecloud.atlassian.net/browse/FE-418?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> refactor: stricter types for graphqlB2B fetch

- apps/storefront/src/pages/PDP/index.tsx
Jira: [B2B-2165](https://bigcommercecloud.atlassian.net/browse/B2B-2165)
- add `useData` hoot as first step refactoring to move data fetching/business logic away from presentational code
- revert this PR
- manual
[B2B-2165]: https://bigcommercecloud.atlassian.net/browse/B2B-2165?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> B2B-2165 refactor PDP - create a useData hook with basic information

- apps/storefront/src/pages/ForgotPassword/index.test.tsx
- apps/storefront/src/utils/basicConfig.ts
Jira: [B2B-2203](https://bigcommercecloud.atlassian.net/browse/B2B-2203)
Using window origin url while login in local env. Right now is creating an incorrect url for the login graphql api call. `/bigcommerce/graphql`
Revert 
login to buyer portal locally
[B2B-2203]: https://bigcommercecloud.atlassian.net/browse/B2B-2203?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: return to window origin locally

- apps/storefront/src/components/table/B3PaginationTable.tsx
- apps/storefront/src/components/table/B3Table.tsx
- apps/storefront/src/pages/Address/index.tsx
- apps/storefront/src/pages/Invoice/components/PrintTemplate.tsx
- apps/storefront/src/pages/Invoice/index.tsx
- apps/storefront/src/pages/QuickOrder/components/QuickOrderB2BTable.tsx
- apps/storefront/src/pages/ShoppingListDetails/components/ShoppingDetailTable.tsx
- apps/storefront/src/pages/ShoppingLists/index.tsx
- apps/storefront/src/pages/quote/components/QuoteDetailTable.tsx
- apps/storefront/src/utils/b3Product/shared/config.ts
- apps/storefront/src/utils/forwardRefWithGenerics.ts
- apps/storefront/src/utils/index.ts
- apps/storefront/src/utils/memoWithGenerics.ts
Jira: [B2B-2150](https://bigcommercecloud.atlassian.net/browse/B2B-2150)
- `B3PaginationTable` was full of `any` types, making it impossible to trace how fetched data was (or wasn't) being used
- The PR attempts to add true, descriptive types without changing the true signature of behaviour
- Small fixes have been made in components which use `B3PaginationTable` where there types were wrong (these mistakes were enabled by `B3PaginationTable` many `any`s)
- 99% just type definition fixes
- Remaining code changes were manually tested
[B2B-2150]: https://bigcommercecloud.atlassian.net/browse/B2B-2150?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> B2B-2150 add Type definitions to B3PaginationTable

- apps/storefront/src/main.ts
- config/deploy/after.sh
Jira: [INFRA-19970](https://bigcommercecloud.atlassian.net/browse/INFRA-19970)
The microapp-cdn URLs were the incorrect URLs to use, they're actually CNAMEd by `microapps.integration/staging` which is what we should be using. This also means the certs would have worked from the get go.
So we can just swap to those URLs and move on with our lives.
The usual rollout process.
Can see the apps exist on those urls
I've also deployed this and verified that buyer portal loads in integration
[INFRA-19970]: https://bigcommercecloud.atlassian.net/browse/INFRA-19970?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: infra-19970 change to microapps url

- apps/storefront/src/pages/AccountSetting/config.ts
- apps/storefront/src/pages/AccountSetting/index.tsx
- apps/storefront/src/pages/AccountSetting/utils.ts
Jira: [B2B-2158](https://bigcommercecloud.atlassian.net/browse/B2B-2158)
Separate payload preparation from the update process.
Purify and simplify handleGetUserExtraFields.
The current logic conflates form validation with form error
display/translations.
We should probably include some form library, but for now we'll just
separate the methods doing the validation from the methods displaying
the errors/alerts.
These two methods are used at different stages of the process and for
different reasons. Separating them allows us to only execute them when
they are needed and more importantly _when_ they are needed.
eg. the `getAccountSettingFiles` is not required for bc users.
Remove the configuration for the `xs` prop, the only use of it is `12`.
Translate the passwordFields directly upon …
> refactor(account-settings): refactor formValidation, updateAccountSettings & dataProcessing

- apps/storefront/src/pages/AccountSetting/config.ts
- apps/storefront/src/pages/AccountSetting/index.tsx
Jira: [B2B-2158](https://bigcommercecloud.atlassian.net/browse/B2B-2158)
Remove the need for translation on lower layers, and lift it up to the view component. b3Lang shouldn't be needed within business logic.
Revert
Manual
[B2B-2158]: https://bigcommercecloud.atlassian.net/browse/B2B-2158?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> refactor(account-settings): lift translations to the view component

- apps/storefront/src/pages/ShoppingLists/ShoppingStatus.tsx
- apps/storefront/src/pages/ShoppingLists/config.ts
- apps/storefront/src/pages/ShoppingLists/index.tsx
Jira: [B2B-2150](https://bigcommercecloud.atlassian.net/browse/B2B-2150)
**N.B.** - this might be easy enough to read as one change, rather than 1 commit at a time
- `getFilterMoreList` created a list of filters that was transformed within the view
- this PR moves all transformations into the `getFilterMoreList` (now the return function of a hook)
- this simplifies the view and takes a step towards more typesafety to help find our IO boundary
- Further work needed within `B3Filter` to workout if or not `getFilterMoreList`'s interface can be further simplified
- Manual Testing 
[B2B-2150]: https://bigcommercecloud.atlassian.net/browse/B2B-2150?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> B2B-2150 fix types and simplify getFilterMoreList within ShippingLists

- apps/storefront/src/components/table/B3PaginationTable.tsx
- apps/storefront/src/components/table/B3Table.tsx
- apps/storefront/src/components/table/PaginationTable.tsx
- apps/storefront/src/components/upload/BulkUploadTable.tsx
- apps/storefront/src/pages/Address/index.tsx
- apps/storefront/src/pages/Dashboard/index.tsx
- apps/storefront/src/pages/Invoice/index.tsx
- apps/storefront/src/pages/QuickOrder/components/QuickOrderB2BTable.tsx
- apps/storefront/src/pages/QuotesList/index.tsx
- apps/storefront/src/pages/UserManagement/index.tsx
- apps/storefront/src/pages/order/Order.tsx
- apps/storefront/src/pages/quote/components/QuoteTable.tsx
- apps/storefront/tests/components/b3table/B3Table.test.tsx
Jira: [B2B-2160](https://bigcommercecloud.atlassian.net/browse/B2B-2160)
- `B3Table` and `B3TablePaginationTable` made prolific use of `any`, losing type safety and a clear view of values
- This PR moves away from the use of `any` by adding more accurate types
- 99% just type definition changes, except for a new `isNodeWrapper` type-guard
**N.B.**
Due to the 'quirky' implementation of these components, some states cannot be legally represented by Typescript.
E.g. if a `selectedSymbol` prop is defined, then it must be a populated key on the `Row` value object
Typescript _could_ represent this if the prop was mandatory, but this is not the case. As such `B3Table` and `B3TablePaginationTable` have numerous type suppressions such as:
```tsx
<Checkbox
// @ts-expect-error typed previously as an …
```
> B2B-2160 Refactor B3Table and B3TablePaginationTable towards type safety

- apps/storefront/src/pages/OrderDetail/components/OrderShipping.tsx
- apps/storefront/src/types/orderDetail.ts
Jira: [B2B-2375](https://bigcommercecloud.atlassian.net/browse/B2B-2375)
This PR changes orders to use `shipping_provider_display_name` from the API instead of `shipping_provider`. This results in properly formatted shipping carriers.
Revert.
Before:
After:
[B2B-2375]: https://bigcommercecloud.atlassian.net/browse/B2B-2375?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: use shipping display name on orders

- apps/storefront/src/utils/b3Product/shared/config.ts
Jira: [B2B-2182](https://bigcommercecloud.atlassian.net/browse/B2B-2182)
When we filter the product based on the type to display the label value of the product select though the pick list we are not displaying the label for products with `Show product image on Storefront` unchecked. So I'm adding the key `product_list` to product `fieldTypes`. The ProductRadio used for pick lists currently only uses `product_list_with_images` as type for a pick list product but `product_list` is also valid type when the option `Show product image on Storefront` is unchecked.
Revert PR
Before:
After:
[B2B-2182]: https://bigcommercecloud.atlassian.net/browse/B2B-2182?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(quote): b2b-2182 adding product list type as field type

- apps/storefront/src/utils/b3ShoppingList/b3ShoppingList.ts
Jira: [B2B-2364](https://bigcommercecloud.atlassian.net/browse/B2B-2364)
Junior buyer does not have permissions to create shopping list on PDP.
The fix is to set `containOrEqual` to `contain` instead of using default `equal` 
My understanding is that Junior buyer's permission contains submit for approval permission, it also has other permissions.
Revert
Manual test with Junior Buyer, Senior Buyer and Admin role and the results are as expected
Junior Buyer Before: Cannot create shopping list
https://github.com/user-attachments/assets/e2ed7fef-a8f1-4031-960c-14a6b11edcdc
Junior Buyer After: Can create shopping list and the status is `draft`
https://github.com/user-attachments/assets/51244583-4155-4c23-a903-b9707bffda79
Senior Buyer behaviour is the same before and after: Can create shopping …
> fix(b2b): b2b-2364  fix permission issue for junior buyer on shopping list creation

- .github/CODEOWNERS
Jira: [PROJECT-7009](https://bigcommercecloud.atlassian.net/browse/PROJECT-7009)
- Add @leeBigCommerce as codeowner
- Remove @LeoChowChina & team-customers
Revert
n/a
[PROJECT-7009]: https://bigcommercecloud.atlassian.net/browse/PROJECT-7009?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore(common): PROJECT-7009 Add @leeBigCommerce as codeowner

- apps/storefront/src/pages/QuoteDetail/index.tsx
Jira: [B2B-2659](https://bigcommercecloud.atlassian.net/browse/B2B-2659)
I'm deleting a snackbar error call when searching for products. Currently when loading a quote detail page we are we are calling `handleGetProductsById`  and the search products in the b3request is throwing a snackbar error so we don't need to a new one to catch the result of `handleGetProductsById`. The second error it has a different format and it seems to be affecting the render of B3Tip.
Revert PR
Cannot test this locally since we don't know yet what configuration in a product is causing the error.
[B2B-2659]: https://bigcommercecloud.atlassian.net/browse/B2B-2659?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(quotes): error when loading quote detail page

- apps/storefront/src/pages/Address/components/SetDefaultDialog.tsx
- apps/storefront/src/pages/QuickOrder/components/QuickOrderFooter.tsx
- apps/storefront/src/pages/QuickOrder/index.tsx
- apps/storefront/src/pages/QuoteDetail/index.tsx
- apps/storefront/src/pages/QuoteDraft/index.tsx
- apps/storefront/src/pages/ShoppingListDetails/components/ShoppingDetailAddNotes.tsx
- apps/storefront/src/pages/ShoppingListDetails/components/ShoppingDetailDeleteItems.tsx
- apps/storefront/src/pages/ShoppingLists/index.tsx
- apps/storefront/src/pages/UserManagement/index.tsx
Jira: [B2B-2619](https://bigcommercecloud.atlassian.net/browse/B2B-2619)
As part of a previous pr, we noticed this css value for justifyContent is invalid.
Took the opportunity to flip `!isMobile` with `isMobile` across the repo.
This value makes the `justifyContent` default to start. Removing all of it so we keep the current behaviour intact.
Revert
Manual
[B2B-2619]: https://bigcommercecloud.atlassian.net/browse/B2B-2619?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(common): B2B-2619 Remove invalid center% value in CSS

- .circleci/config.yml
Jira: [B2B-2710](https://bigcommercecloud.atlassian.net/browse/B2B-2710)
Before this, even if linting and/or unit tests failed, we are still able to merge the PR
Revert
Passing CI
When linting failed:
When unit tests failed:
[B2B-2710]: https://bigcommercecloud.atlassian.net/browse/B2B-2710?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore(common): B2B-2710 Require testing and linting to pass before allowing to merge

- apps/storefront/src/components/HeadlessController.tsx
- commit-validation.json
Passing `productId` to the created item for the add to shopping list feature to work. Also reading the item from the window object since we were losing the reference after a new render
revert
https://github.com/user-attachments/assets/dfb352ee-af4d-42ab-ab1a-46d5da78fb1a
> fix(catalyst): fixing product object for shopping list add operation

- apps/storefront/src/pages/Invoice/utils/payment.ts
- apps/storefront/src/pages/quote/utils/quoteCheckout.ts
- commit-validation.json
Redirecting catalyst storefronts' B2B checkout workflows to the catalyst internal `/checkout` route passing a cart id as a search param to create the redirect url
revert
https://github.com/user-attachments/assets/25925e22-2531-4282-b076-8c369f5ddc33
> fix(catalyst): redirecting catalyst sf to checkout route

- apps/storefront/vite.config.ts
- docs/headless.md
Adding environment variable `VITE_DISABLE_BUILD_HASH` to remove hashes from entry files for custom buyer portal users.
revert
build without hashes in names:
before:
> feat(common): optionally remove hashes from entry filenames

- apps/storefront/src/components/captcha/Captcha.tsx
- apps/storefront/src/pages/ForgotPassword/index.test.tsx
- apps/storefront/src/pages/ForgotPassword/index.tsx
- apps/storefront/src/pages/Login/config.ts
- apps/storefront/src/pages/Login/index.tsx
- apps/storefront/src/pages/Registered/RegisterComplete.tsx
- apps/storefront/src/pages/Registered/RegisterContent.tsx
- apps/storefront/src/pages/Registered/RegisteredAccount.tsx
- apps/storefront/src/pages/Registered/RegisteredFinish.tsx
- apps/storefront/src/pages/Registered/context/RegisteredContext.tsx
- apps/storefront/src/pages/Registered/index.tsx
- apps/storefront/src/pages/RegisteredBCToB2B/index.tsx
- apps/storefront/src/shared/service/bc/graphql/login.ts
Jira: [B2B-2146](https://bigcommercecloud.atlassian.net/browse/B2B-2146)
The login after registration functionality was trying to find email &
password on the global "registration" state. Since the state is quite
big and convoluted it meant looping through all the fields to find the
customer's email and password.
By explicitly exposing it we remove the dependency on global state and
make the code simpler.
Rename for consistency:
- `emailAddress` -> `email`
- `pass` -> `password`
Remove `storeName` from the RegisteredContext, all we are doing is
reading it from global and saving it in local context.
Revert
Manual
[B2B-2146]: https://bigcommercecloud.atlassian.net/browse/B2B-2146?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> refactor(account): B2B-2146 Use local instead of global state for login after registration

- apps/storefront/src/utils/cartUtils.ts
- commit-validation.json
- packages/hooks/useB2BCallback.ts
Creating a new event `on-cart-created` so headless storefronts can sync cart ids easier
Revert
Created a cart and listened to the event
> feat(carts): on cart created callback

- apps/storefront/src/pages/Address/components/DeleteAddressDialog.tsx
- apps/storefront/src/pages/Address/components/SetDefaultDialog.tsx
- apps/storefront/src/pages/Address/index.tsx
- apps/storefront/src/shared/service/b2b/graphql/address.ts
- commit-validation.json
Jira: [B2B-2154](https://bigcommercecloud.atlassian.net/browse/B2B-2154)
- use a single useState to control which dialog is open
- reduce api shared with children components, `closeDialog` instead of `setIsOpen`
- helper to check config
- add missing dependencies to react hooks
Revert
https://github.com/user-attachments/assets/af7ed7ad-9b70-4287-bc12-0bb7eafc0a4d
[B2B-2154]: https://bigcommercecloud.atlassian.net/browse/B2B-2154?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> refactor(addresses): B2B-2154 Use a single useState for all dialog controls

- apps/storefront/.dependency-cruiser.cjs
- apps/storefront/package.json
- apps/storefront/src/pages/QuotesList/index.test.tsx
- apps/storefront/src/shared/service/b2b/graphql/orders.ts
- apps/storefront/src/shared/service/b2b/graphql/quote.ts
- apps/storefront/src/shared/service/b2b/graphql/shoppingList.ts
- apps/storefront/tests/builder.ts
- apps/storefront/tests/global-setup.ts
- apps/storefront/tests/setup-test-environment.ts
- apps/storefront/tests/storeStateBuilders/index.ts
- apps/storefront/tests/storeStateBuilders/storeInfoStateBuilder.ts
- apps/storefront/tests/test-utils.tsx
- apps/storefront/vite.config.ts
- packages/eslint-config-b2b/.eslintrc.js
- yarn.lock
**N.B.**
- Add some basic, happy-path tests to the Quotes Listing page
- Not meant to be exhaustive, coupled to APIs, but a reasonable start
- Revert if needed
> refactor(quotes): add basic test harness to quotes listing page

- apps/storefront/src/pages/UserManagement/index.test.tsx
- apps/storefront/src/shared/service/b2b/graphql/users.ts
- apps/storefront/tests/test-utils.tsx
- commit-validation.json
**N.B.**
- Add some basic, happy-path tests to the User Management page
- Not meant to be exhaustive, coupled to APIs, but a reasonable start
- Revert if needed
> refactor(quotes): B2BCAT-22 add basic test harness to user management page

- apps/storefront/src/pages/QuoteDetail/index.test.tsx
- apps/storefront/src/shared/service/b2b/graphql/product.ts
- apps/storefront/src/shared/service/b2b/graphql/quote.ts
- apps/storefront/src/store/slices/company.ts
- apps/storefront/tests/builder.ts
Jira: [B2BCAT-16](https://bigcommercecloud.atlassian.net/browse/B2BCAT-16)
**N.B.**
- Add some basic, happy-path tests to the Quotes Details page
- Not meant to be exhaustive, coupled to APIs, but a reasonable start
- Revert if needed
[B2BCAT-16]: https://bigcommercecloud.atlassian.net/browse/B2BCAT-16?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> refactor(quotes): B2BCAT-16 add basic test harness to quote details page

- apps/storefront/src/shared/service/bc/graphql/currency.ts
- apps/storefront/src/shared/service/request/b3Fetch.ts
- apps/storefront/src/utils/b3CurrencyFormat.ts
When adding a new product to a draft quote we are seeing the price and currency always as the default currency instead of the one selected in the storefront. That happens because when we are getting the active currency we are using the bc proxy request to get the information, so the session in the proxy is not being sync properly since the change is coming from a stencil store. In stencil stores we don't have to use the proxy. Adding a validation to handle the request based on the platform will have stencil and headless stores using the correct flow.
Revert PR
https://github.com/user-attachments/assets/5b697758-d933-4133-a429-1a1b1620810f
> fix(quotes): B2B-2415 getting site configs stencil request

- apps/storefront/src/components/HeadlessController/index.tsx
- apps/storefront/src/hooks/useB3AppOpen.ts
- apps/storefront/src/index.d.ts
- packages/global-b3/index.ts
Jira: [B2B-2880](https://bigcommercecloud.atlassian.net/browse/B2B-2880)
When loading catalyst checkout as a guest and clicking the Sign In button it gets redirected into a stencil page, becase the buyer portal configs map an event listener into the sign in and gets tracked by the apps/storefront/src/hooks/useB3AppOpen.ts file, so in order to detach this event listener and others, we need to expose a function that could be use by B2B checkout and override this.
Revert this PR
https://github.com/user-attachments/assets/7ca8a851-6a0f-4d27-95b9-a9056c0b1a08
[B2B-2880]: https://bigcommercecloud.atlassian.net/browse/B2B-2880?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(common): B2B-2880 allow a way to override buyer portal event listener for sign in

- apps/storefront/src/components/HeadlessController/getSku.tsx
Jira: [B2BCAT-25](https://bigcommercecloud.atlassian.net/browse/B2BCAT-25)
Allow `selectedOptions` to be `undefined` when adding products to quote.
For products that don't have options, we don't need to provide an array. 
Revert
https://github.com/user-attachments/assets/ffd605ae-11c4-4c45-9bf9-42c6b52eb657
https://github.com/user-attachments/assets/1da3757b-bed2-4c6e-a11f-ade43c9fa026
[B2BCAT-25]: https://bigcommercecloud.atlassian.net/browse/B2BCAT-25?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(headless): B2BCAT-25 Allow for empty selectedOptions array

- apps/storefront/src/pages/ShoppingListDetails/index.test.tsx
- apps/storefront/src/shared/service/b2b/graphql/shoppingList.ts
- apps/storefront/tests/test-utils.tsx
Jira: [B2BCAT-17](https://bigcommercecloud.atlassian.net/browse/B2BCAT-17)
**N.B.**
- Best read one commit at a time (each commit builds and tests pass at all times)
- Existing tests mocked graphQL queries incorrectly (one mock accidentally resolved _all_ queries)
- Existing tests mocked internal permission logic
- Existing tests did not yet use faker or builders based on strict types
- Revert 
- Refactored tests
[B2BCAT-17]: https://bigcommercecloud.atlassian.net/browse/B2BCAT-17?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3 …
> refactor(quotes): B2BCAT-17 change shopping lists test to use graphql mocks

- apps/storefront/src/pages/UserManagement/index.test.tsx
- apps/storefront/src/shared/service/b2b/graphql/users.ts
**N.B.**
- Add happy path test for editing a user
- Add happy path test for deleting a user
- Add happy path test for moving to the next page
- Add happy path test for moving to the previous page
- Revert if needed
> refactor(user-management): B2BCAT-22 add tests for editing and deleting in Users Management

- apps/storefront/src/pages/OrderDetail/components/OrderBilling.tsx
When loading digital products in OrderDetails page we use OrderBilling component to render the products and right now we are not passing the money prop of the order loaded so instead of using the currency from the order it's using the active currency in the storefront to display the symbol of the products.
Revert PR
Before:
https://github.com/user-attachments/assets/2f229f38-5b2e-404f-af44-975badf66e4d
After: 
https://github.com/user-attachments/assets/16a353ee-2edb-442f-9d72-a23ec3241acc
> fix(orders): B2B-2820 passing money data to products list

- apps/storefront/src/components/B3Tip.tsx
Jira: [JIRA_2508](https://bigcommercecloud.atlassian.net/browse/B2B-2508)
Need to increase width of the snackbar notification to align with designs and improve user experience.
Standard rollout + rollback procedure.
Before:
After:
> fix(common): B2B-2508 Width of notifications

- apps/storefront/src/components/HeadlessController/index.tsx
- apps/storefront/src/index.d.ts
Jira: [B2B-2831](https://bigcommercecloud.atlassian.net/browse/B2B-2831)
getList function to useShoppingLists hook so we can use it in the HeadlessController too
revert
SDK usage in console
[B2B-2831]: https://bigcommercecloud.atlassian.net/browse/B2B-2831?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(shopping-lists): adding get shopping lists to SDK

- apps/storefront/src/pages/UserManagement/index.test.tsx
**N.B.** enable "hide whitespace" as this adds a describe to a lot of tests
- Add a describe wrapper that runs the User Management tests in both mobile and desktop mode
- Unlike most pages, User Management uses the same underlying components for both
- Revert
- New tests, no user facing code changed
> refactor(user-management): B2BCAT-22 ensure tests run for mobile and desktop size for Users Management

- apps/storefront/src/pages/UserManagement/getUserExtraFields.ts
- apps/storefront/src/pages/UserManagement/index.test.tsx
- Fix bug where custom multiline fields never received their configured number of rows
- Add test coverage for custom fields within User Management
- Revert
- New tests
> refactor(user-management): B2BCAT-22 add tests for custom field in Users Management

- apps/storefront/src/pages/UserManagement/index.test.tsx
- apps/storefront/src/pages/UserManagement/index.tsx
- apps/storefront/src/shared/service/b2b/graphql/users.ts
- apps/storefront/src/shared/service/b2b/index.ts
- apps/storefront/src/shared/service/request/b3Fetch.ts
**N.B.** Best read a commit at a time
- extend `graphqlB2B` to be type safe (but fallback to current vague-ness by default)
- add type definition to `getUsers`
- move `getUsers` to use true graphql variables
- update `UserManagement` to define its `filterSearch` as the new `GetUsersVariables`
- Revert
- Updated tests (to match new `variables` usage in the query)
- Passing feature tests
https://github.com/user-attachments/assets/eaf5d2c6-8da2-4f56-8eb9-a5630c2365fc
> refactor(user-management): B2BCAT-22 improve type safety of graphqlB2B and thus getUsers

- apps/storefront/src/components/upload/B3Upload.tsx
- apps/storefront/src/components/upload/B3UploadLoading.tsx
- apps/storefront/src/components/upload/utils.ts
Jira: [B2B-2842](https://bigcommercecloud.atlassian.net/browse/B2B-2842)
This PR adds the CSV extension as a fallback for uploads in the `B3Upload` component. This is to fix a bug where Firefox reports the wrong MIME type for CSV files on Windows machines with Excel installed.
It also includes some slight refactoring/cleanup.
Revert.
https://github.com/user-attachments/assets/03f23271-46e5-46cb-8099-4897d47bbf57
[B2B-2842]: https://bigcommercecloud.atlassian.net/browse/B2B-2842?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(orders): B2B-2842 Add csv extension fallback to upload component

- apps/storefront/src/pages/UserManagement/index.test.tsx
- apps/storefront/src/shared/service/b2b/graphql/users.ts
- Fix issue where the User Management search returns no results unless a role filter is used
1. The view models the _lack_ of a company role filter as an empty string `''`
2. The anti-corruption for the graphql query fed this value through `Number(data.companyRoleId)`
3. `Number('')` returns `0`
4. That `0` is then honoured as a filter value be the BE
5. As no users match that role id, none are returned
https://github.com/user-attachments/assets/b0e913ac-e060-40f2-a7ed-9670d47bd5f7
https://github.com/user-attachments/assets/79f2d86d-61ca-4e33-a4b6-bfee99beb0ff
- New test added to ensure a lack of role filter reaches the BE as `undefined`
[B2BCAT-22]: …
> fix(user-management): B2BCAT-22 fix user management role id filter

- apps/storefront/src/pages/UserManagement/index.test.tsx
- apps/storefront/tests/test-utils.tsx
Jira: [B2BCAT-40](https://bigcommercecloud.atlassian.net/browse/B2BCAT-40)
- Move alert setup out of the User Management test file and into the `renderWithProviders` util
- Allows other tests to benefit from the setup, without adding noise to their own setup
- Revert
- Testing only, no user facing code changed
[B2BCAT-40]: https://bigcommercecloud.atlassian.net/browse/B2BCAT-40?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> refactor(user-management): B2BCAT-40 move alerts setup out to renderWithProviders

- apps/storefront/src/components/ConfirmMasqueradeDialog.tsx
- apps/storefront/src/components/layout/B3RenderRouter.tsx
- apps/storefront/src/components/outSideComponents/B3MasqueradeGlobalTip.tsx
Jira: [B2B-2993](https://bigcommercecloud.atlassian.net/browse/B2B-2993)
Removing `closeMasquerade` search param usage as it was never implemented correctly. Also increasing modal zIndex so it can be display above the buyer portal UI.
Revert
[B2B-2993]: https://bigcommercecloud.atlassian.net/browse/B2B-2993?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(dashboard): B2B-2993 removing unused closeMasquerade param

- config/deploy/after.sh
Using store hashes from tier 1 list directly as variables in the after config script due to problems when reading the prod tier 1 json file.
Revert
WIP
> feat(common): B2B-3031 using store hash as variable

- apps/storefront/src/components/layout/B3CloseAppButton.tsx
When logging as a customer we are redirected to STORE_URL.com/account.php?action=order_status#/orders but when using the close button is possible to see the storefront's order view which is causing confusion for the users. 
So if we are located in a page with search action=order_status we need to be redirected to the home page of the storefront.
Revert
Before:
https://github.com/user-attachments/assets/908df075-b0f9-45e3-8679-28fa5387c360
After:
https://github.com/user-attachments/assets/bfa7b9c3-fedd-4c56-a555-dd7e4b9911ca
> fix(common): B2B-2812 update close button to not show order views

- apps/storefront/src/pages/QuickOrder/components/ChooseOptionsDialog.tsx
- apps/storefront/src/pages/QuickOrder/components/ProductListDialog.tsx
- apps/storefront/src/pages/QuickOrder/components/QuickAdd.tsx
- apps/storefront/src/pages/QuickOrder/components/QuickOrderPad.tsx
- apps/storefront/src/pages/QuickOrder/components/SearchProduct.tsx
- commit-validation.json
Jira: [B2BCAT-18](https://bigcommercecloud.atlassian.net/browse/B2BCAT-18)
These 3 components were reused from shoppingLists, decouple them so we
can narrow the use-cases.
Revert
First commit is a straight copy of the current components in `ShoppingList/*`
Second commit is about in-lining variables and removing unused props.
[B2BCAT-18]: https://bigcommercecloud.atlassian.net/browse/B2BCAT-18?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> refactor(quick-order): B2BCAT-18 Decouple searchProducts/ProductListDialog/ChooseOptionsDialog

- apps/storefront/src/components/outSideComponents/B3CompanyHierarchyExternalButton.test.tsx
- commit-validation.json
Jira: [B2BCAT-21](https://bigcommercecloud.atlassian.net/browse/B2BCAT-21)
- Add test for the Company Hierarchy External Button
- better recognised as the "Your are representing X Company" dialogue
- Revert
- No user facing features changes, new tests only
[B2BCAT-21]: https://bigcommercecloud.atlassian.net/browse/B2BCAT-21?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> refactor(company-hierarchy): B2BCAT-21 add test harness for Company Hierarchy External Button

- .github/workflows/deploy-staging.yml
Jira: [3215](https://bigcommercecloud.atlassian.net/browse/3215)
As part of the following up actions for Onboarding into cortex project we need to prevent the automatic deploy to AWS staging environment when we push changes to main
Revert this PR
Workflow related cleanup, no tests available
> fix(common): B2B-3215 automatic deploy to AWS staging removed

- apps/storefront/tests/setup-test-environment.ts
Jira: [B2BCAT-21](https://bigcommercecloud.atlassian.net/browse/B2BCAT-21)
Add an ignore for `ImmutableStateInvariantMiddleware` to the `failOnConsole` tool.
This warning needs fixing, but it is probably all too messy atm to try and debug it.
Revert
This PR should not fail its tests
[B2BCAT-21]: https://bigcommercecloud.atlassian.net/browse/B2BCAT-21?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(common): B2BCAT-21 Ignore ImmutableStateInvariantMiddleware warnings in production

- apps/storefront/src/components/form/B3ControlSelect.tsx
- apps/storefront/src/pages/CompanyOrderList/index.mobile.test.tsx
- apps/storefront/src/pages/CompanyOrderList/index.test.tsx
- apps/storefront/src/pages/MyOrders/index.mobile.test.tsx
- apps/storefront/src/pages/MyOrders/index.test.tsx
- apps/storefront/src/pages/order/Order.tsx
- apps/storefront/src/pages/order/shared/getOrderStatus.ts
- commit-validation.json
Jira: [B2BCAT-12](https://bigcommercecloud.atlassian.net/browse/B2BCAT-12)
Note: First commit is a continuation of `B2BCAT-11`. Some missing bits.
- Include SuperAdmin masquerading tests on mobile
- Improve combobox accessibility, make labels work + use them in the tests
- Add type annotations for `getColumnItems`, remove default value
- Remove unused `getOrderStatusOptions` method
Revert
This PR is mostly testing, there are some tiny changes but mostly types.
[B2BCAT-12]: https://bigcommercecloud.atlassian.net/browse/B2BCAT-12?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> test(company-orders): B2BCAT-12 Add test harness for CompanyOrders

- apps/storefront/src/components/B3Tip.tsx
- apps/storefront/src/components/HeadlessController/index.tsx
- apps/storefront/src/components/TipBody.test.tsx
- apps/storefront/src/components/TipBody.tsx
- apps/storefront/src/hooks/dom/useCartToQuote.ts
- apps/storefront/src/hooks/dom/utils.ts
- apps/storefront/src/index.d.ts
- apps/storefront/src/pages/Invoice/components/B3Pulldown.tsx
- apps/storefront/src/pages/Invoice/components/InvoiceFooter.tsx
- apps/storefront/src/pages/OrderDetail/components/OrderDialog.tsx
- apps/storefront/src/pages/PDP/addProductsToShoppingListErrorHandler.ts
- apps/storefront/src/pages/PDP/index.test.tsx
- apps/storefront/src/pages/PDP/useAddedToShoppingListAlert.tsx
- apps/storefront/src/pages/QuickOrder/components/QuickAdd.tsx
- apps/storefront/src/pages/QuickOrder/components/QuickOrderFooter.tsx
- apps/storefront/src/pages/QuickOrder/components/QuickOrderPad.tsx
- apps/storefront/src/pages/QuickOrder/utils.ts
- apps/storefront/src/pages/QuoteDetail/index.tsx
- apps/storefront/src/pages/ShoppingListDetails/components/AddToShoppingList.tsx
- apps/storefront/src/pages/ShoppingListDetails/components/QuickAdd.tsx
- apps/storefront/src/pages/ShoppingListDetails/components/ReAddToCart.tsx
- apps/storefront/src/pages/ShoppingListDetails/components/ShoppingDetailFooter.tsx
- apps/storefront/src/pages/ShoppingListDetails/index.tsx
- apps/storefront/src/pages/quote/components/AddToQuote.tsx
- apps/storefront/src/shared/dynamicallyVariable/context/config.ts
- apps/storefront/src/utils/b3Tip.ts
- packages/lang/locales/en.json
Jira: [B2B-2626](https://bigcommercecloud.atlassian.net/browse/B2B-2626)
This PR refactors our toast system to make it simpler and adaptable to our new Catalyst storefront plus other headless integrations. 
Some extra cleanup was made within our types as we introduced a TipBody to remove the jsx prop supplied to several custom notifications. 
We could not consolidate global notifs and local notifs in this PR since stencil has a custom behavior where notifications dispatched inside an iframe cannot be visible in the stencil page. We could do something like this:
```js
snackbar.success('', { type: 'global' }) // add a type prop for global/local
```
But we think this is out of the scope of this PR as its getting big. 
Revert
https://github.com/user-attachments/assets/0360d8de-77d4-4e84-832a-5 …
> feat(catalyst): B2B-2626 native catalyst notifications

- apps/storefront/src/pages/CompanyOrderList/index.mobile.test.tsx
- apps/storefront/src/pages/CompanyOrderList/index.test.tsx
- apps/storefront/src/pages/MyOrders/index.mobile.test.tsx
- apps/storefront/src/pages/MyOrders/index.test.tsx
- apps/storefront/src/pages/order/orders.ts
- apps/storefront/src/types/order.ts
Jira: [B2BCAT-39](https://bigcommercecloud.atlassian.net/browse/B2BCAT-39), [B2BCAT-12](https://bigcommercecloud.atlassian.net/browse/B2BCAT-12)
As part of a previous commit we remove much of the fluff retrieved by
the APIs that wasn't even used as part of the MyOrders page.
We forgot to remove a couple of instances in the tests.
Apply the same changes to the recently merged `CompanyTestHarnesses`.
Revert
This PR is mainly test files. Passing tests should prove this works as expected.
[B2BCAT-39]: https://bigcommercecloud.atlassian.net/browse/B2BCAT-39?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[B2BCAT-12]: https://bigcommercecloud.atlassian.net/browse/B2BCAT-12?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViL …
> test(orders): Simplify CompanyOrders/MyOrders data types

- apps/storefront/src/pages/Invoice/index.test.tsx
Jira: [B2BCAT-13](https://bigcommercecloud.atlassian.net/browse/B2BCAT-13)
Invoices with status = Open do not show the view payment history link, this is causing some flakiness in the test. This commit hardcodes the status to PartiallyPaid to ensure it always shows.
Revert 🤷 
Running the flaky test 20 times in a row:
[B2BCAT-13]: https://bigcommercecloud.atlassian.net/browse/B2BCAT-13?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> test(invoices): B2BCAT-13 Ensure View payment history is always available in the test

- apps/storefront/src/components/table/B3PaginationTable.tsx
- apps/storefront/src/pages/ShoppingListDetails/components/ShoppingDetailTable.tsx
- apps/storefront/src/pages/ShoppingListDetails/index.test.tsx
- apps/storefront/src/pages/ShoppingListDetails/index.tsx
Context - Fixed selection resetting when updating quantity, notes, or options in the table
Bug - https://bigcommercecloud.atlassian.net/browse/B2B-3301
Changes:
Added `PRESERVE_SELECTION`  to the B3PaginationTable to avoid setting the selection during the internal table refresh
https://www.loom.com/share/d22c496131d2428fbb05d7638353a0f6
Added for B3PaginationTable as most logic of this PR was sitting here
https://github.com/bigcommerce/b2b-buyer-portal/pull/463
> fix(shopping-lists): B2B-3301 Fixed selection resetting when updating quantity, notes, or options in the table

- apps/storefront/src/hooks/dom/utils.test.ts
Jira: [B2B-3329](https://bigcommercecloud.atlassian.net/browse/B2B-3329)
This PR adds unit tests for adding a product to a quote from the product detail (PDP) page. This area was lacking coverage that we need for the backordering enablement project.
All unit tests passing.
Code coverage on `utils.ts` before:
Code coverage on `utils.ts` after:
[B2B-3329]: https://bigcommercecloud.atlassian.net/browse/B2B-3329?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> test(quotes): B2B-3329 Add unit tests for adding product to quote from PDP page

- apps/storefront/package.json
- yarn.lock
Jira: [B2BCAT-90](https://bigcommercecloud.atlassian.net/browse/B2BCAT-90)
Remove c8, not used, prompted by:
- https://github.com/bigcommerce/b2b-buyer-portal/pull/492
Revert
[B2BCAT-90]: https://bigcommercecloud.atlassian.net/browse/B2BCAT-90?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore(deps): B2BCAT-90 Remove c8 (not used)

- apps/storefront/src/pages/Invoice/components/InvoiceStatus.tsx
Jira: [B2B-3294](https://bigcommercecloud.atlassian.net/browse/B2B-3294)
Missing translations for Invoice table statuses column 
Revert
[B2B-3294]: https://bigcommercecloud.atlassian.net/browse/B2B-3294?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(invoices): B2B-3294 Added translations for Invoice statuses

- rfc/graphql-schema/additionalTypeDefs/byPage/draftQuote.ts
- rfc/graphql-schema/additionalTypeDefs/index.ts
Jira: [B2BCAT-66](https://bigcommercecloud.atlassian.net/browse/B2BCAT-66)
- Draft of the schema needed to drive the Draft Quote page
In this schema I have chosen to keep "Draft" as a status on a unified "Quote" type/entity, rather than give it its own
As such, mutations only applicable to Drafts appear under the `quote` namespace, but can technically only be applied to true Drafts. For example, `quote. updateLineItem` will need to return an error for all but "Draft" status quotes.
If we had seperate `DraftQuote`, `OpenQuote`, `ExpiredQuote`, `OrderedQuote` and `ArchivedQuote` types they would exact same schemas (possibly with just `expirationDate` needing to be optional to suite `DraftQuotes`)
Keeping individual types would lead us to use different mutation namespaces. If we did, there …
> docs(quotes): B2BCAT-66 Add schemas for Draft Quote

- docs/headless.md
- docs/stencil.md
Jira: [B2B-3452](https://bigcommercecloud.atlassian.net/browse/B2B-3452)
Removing all references to the `/assets` route for the VITE_ASSETS_ABSOLUTE_PATH from the documentation since we no longer need this in our build process.
Revert
Build success:
Deployed build:
https://test-store-w2.mybigcommerce.com/
[B2B-3452]: https://bigcommercecloud.atlassian.net/browse/B2B-3452?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> docs(common): B2B-3452 removing required /assets route in env variable

- apps/storefront/src/hooks/dom/useMyQuote.ts
- apps/storefront/src/hooks/dom/utils.test.ts
- apps/storefront/src/hooks/dom/utils.ts
- apps/storefront/src/shared/service/b2b/graphql/product.ts
Jira: [B2B-3325](https://bigcommercecloud.atlassian.net/browse/B2B-3325)
This PR adds functionality that calls the new product validation GQL query when adding a product to a quote from the product detail page (PDP). It is gated behind the backordering feature flag.
In stock:
https://github.com/user-attachments/assets/e24848d0-2460-4abd-9df6-585736b05767
Out of stock:
https://github.com/user-attachments/assets/061a91c7-7ce7-45a1-b202-18e88557199e
Backordered:
https://github.com/user-attachments/assets/aa6f570e-a80f-482a-9e6f-6c1cc2970d50
[B2B-3325]: https://bigcommercecloud.atlassian.net/browse/B2B-3325?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(quotes): B2B-3325 Call validation query when adding products from PDP

- apps/storefront/src/pages/QuickOrder/index.main.test.tsx
- apps/storefront/src/pages/QuoteDraft/index.test.tsx
- apps/storefront/src/pages/ShoppingListDetails/index.test.tsx
- apps/storefront/src/shared/service/b2b/graphql/product.ts
Jira: [B2B-3330](https://bigcommercecloud.atlassian.net/browse/B2B-3330)
In order to make sure that the backordering changes do not cause regressions we are making sure that the behavior of adding to draft quote still works as expected.
Revert this PR
[B2B-3330]: https://bigcommercecloud.atlassian.net/browse/B2B-3330?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(common): B2B-3330 buyer portal unit test adding to draft quote

- apps/storefront/src/pages/QuickOrder/components/QuickOrderFooter.tsx
- apps/storefront/src/pages/QuickOrder/index.main.test.tsx
- apps/storefront/src/pages/ShoppingListDetails/components/ShoppingDetailFooter.tsx
- apps/storefront/src/pages/ShoppingListDetails/index.test.tsx
- apps/storefront/src/utils/storefrontConfig.ts
- apps/storefront/src/utils/validateProducts.ts
Jira: [B2B-3509](https://bigcommercecloud.atlassian.net/browse/B2B-3509)
This PR adds calls to the `validateProduct` GQL query when adding products to a quote via quick order and shopping lists. These changes are gated behind the backordering feature flag.
Shopping list:
https://github.com/user-attachments/assets/84f8b2a4-be17-43aa-adca-7b5c78b2a5c8
Quick order:
https://github.com/user-attachments/assets/5419789f-e601-41c6-be06-81b114302f2a
[B2B-3509]: https://bigcommercecloud.atlassian.net/browse/B2B-3509?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(quotes): B2B-3509 Call validate product query in quick order and shopping lists

- apps/storefront/src/shared/service/request/base.ts
Jira: [B2B-3297](https://bigcommercecloud.atlassian.net/browse/B2B-3297)
Updating the staging app_client_id to reflect the new BigCommerce staging environment.
Revert
Needs to be released to properly test this configuration. Will revert if staging environment has any issues.
[B2B-3297]: https://bigcommercecloud.atlassian.net/browse/B2B-3297?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore(common): B2B-3297 update staging app_client_id

- apps/storefront/src/App.tsx
- apps/storefront/src/constants/index.ts
- apps/storefront/src/pages/Registered/index.tsx
- apps/storefront/src/shared/routes/index.tsx
- commit-validation.json
Jira: [B2B-3501](https://bigcommercecloud.atlassian.net/browse/B2B-3501)
This commit redirects the user back to checkout when the `redirectTo=check-out` param is present.
This enhances the flow where a user click "create account" in checkout, as it takes them back to where they were after registration.
As part of this same change, we've tighten the detection of certain scenarios, making sure we avoid certain false~positives when detecting checkout/change_password/etc.
This is the second attempt at trying to honour the `redirectTo` query param in buyer portal to redirect users back to checkout.
In the previous attempt, the pathname was set to `/` even if there was no original hash in the url, this caused a `/#/` to always show.
This commit minimised the amount of change to …
> feat(register): B2B-3501 Honour `?redirectTo=check-out after registration (second try)

- apps/storefront/src/pages/quote/components/QuoteDetailTable.tsx
Jira: [B2B-3531](https://bigcommercecloud.atlassian.net/browse/B2B-3531)
$ symbol showing in front of product variants and values in account details page
Revert
Note: Code was removed in this [commit](https://github.com/bigcommerce/b2b-buyer-portal/commit/a5ec5e96671cafd128b9c727009b0894270c9cf9)
[B2B-3531]: https://bigcommercecloud.atlassian.net/browse/B2B-3531?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(quotes): B2B-3531 fix for product variants showing $ symbol in quote details page 

- apps/storefront/src/pages/QuoteDraft/index.test.tsx
- apps/storefront/src/pages/QuoteDraft/index.tsx
- apps/storefront/src/shared/service/b2b/graphql/quote.ts
- Currently users with a custom role an no permission addresses aren't able to submit a quote because the api call throws an error and breaks the flow of the code, so it never reaches the part where the customer info is updated in the state and that information is required to submit the quote.
Revert 
Before:
https://github.com/user-attachments/assets/251f522c-a1c7-4cd2-a29c-52be4b0085c0
After: 
https://github.com/user-attachments/assets/66badc22-c59d-4848-8791-dee1b4a490e8
> fix(quotes): B2B-3456 fix submit draft quote flow for users with no address permissions

- apps/storefront/src/hooks/dom/utils.test.ts
- apps/storefront/src/pages/QuickOrder/index.main.test.tsx
- apps/storefront/src/pages/QuickOrder/index.quickpad.test.tsx
- apps/storefront/src/pages/QuoteDraft/index.test.tsx
- apps/storefront/src/pages/QuoteDraft/index.tsx
- apps/storefront/src/pages/ShoppingListDetails/components/ChooseOptionsDialog.tsx
- apps/storefront/src/pages/ShoppingListDetails/index.test.tsx
- apps/storefront/src/pages/quote/shared/utils.ts
- apps/storefront/src/shared/service/b2b/graphql/product.ts
- apps/storefront/src/utils/b3Product/b3Product.ts
Jira: [B2B-3688](https://bigcommercecloud.atlassian.net/browse/B2B-3688)
This PR uses the `availableToSell` and `unlimitedBackorder` values returned by the `productsSearch` API to properly display `TBD` instead of product price for backordered products. These changes are gated behind the backordering feature flag.
Before (TBD always shows for backordered products):
https://github.com/user-attachments/assets/3e979d8b-4cee-490d-8cdf-1e97f5773dee
After (TBD only shows when requested quantity is greater than available to sell quantity):
https://github.com/user-attachments/assets/56f3bdc8-f8e4-45df-9976-8660ebf4aac0
Unit tests were also added.
[B2B-3688]: https://bigcommercecloud.atlassian.net/browse/B2B-3688?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJ …
> fix(quotes): B2B-3688 Properly show TBD as price for backordering

- apps/storefront/src/pages/QuickOrder/components/QuickOrderFooter.tsx
- apps/storefront/src/pages/ShoppingListDetails/components/ShoppingDetailFooter.tsx
In our new backendValidation function we were not using the current functionality that transforms the lineItems object to the one required by the cart create query. So I'm reusing the implementation and using it in both front end and backend validation functions. Since the lineitems optionList was not prepared for the query it was causing errores when adding a purchased product to the cart.
Revert
https://github.com/user-attachments/assets/e3c619e4-79e7-43f6-b176-dae19ae3c92d
> fix(orders): B2B-3691 use searchproduct information to create line items object
